### ISSUE TITLE
Can't scroll down table when uploading

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#102]
In Chrome I can't find a way to scroll down the sites table with this excel file:
[SheepCreekMagICUpload.xlsx](https://github.com/earthref/MagIC/files/1093494/SheepCreekMagICUpload.xlsx)
<img width="1078" alt="screen shot 2017-06-21 at 7 56 35 pm" src="https://user-images.githubusercontent.com/1278789/27415454-e54b9aa2-56bb-11e7-94d5-7e723d0e598c.png">

**Comment by rminnett** [comment]
Did you preview more rows first? I know this isn't as intuitive as having
all of the data there, so I'll improve this soon.

**Comment by njarboe** [comment]
Preview more rows works. Having a show all rows would be nice. Will add as new issue.
