### ISSUE TITLE
After a private contribution is activated should it be gone from the private workspace?

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#104]
After a private contribution is activated should it be gone from the private workspace?
I think so. This is currently not the case. Rene 2013 activated and still in private workspace.
<img width="1174" alt="screen shot 2017-06-21 at 9 42 42 pm" src="https://user-images.githubusercontent.com/1278789/27417624-9d2f009c-56ca-11e7-9fd3-3caea0b94d9c.png">

**Comment by rminnett** [comment]
Yes, perhaps for now. My plan is to show the activated contributions, but in a separate tab so they're not so distracting.

**Comment by njarboe** [comment]
That would be great. I would say don't do a partial fix and wait till you
have time to implement a new tab. Not high on the list but when people
start having many activated contributions it will be good to have.

**Comment by rminnett** [comment]
Done
