### ISSUE TITLE
When doing an action, like delete or adding a DOI (etc.) show that an action is in progress.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#107]
When deleting a private contribution, it takes quite a few seconds (I have seen up to about 10s) and the contribution that one deleted is still on the screen. Many actions take a bit of time and there is no indiction that the system is working on completing the task. This is a bit confusing. I'm not sure how to inform the user that the system is working but something like the standard hourglass or rainbow ball would be nice.

**Comment by rminnett** [comment]
This will be addressed by #427
