### ISSUE TITLE
Need a "None" option on the Import Template list

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#110]
Need a "None" option on the Import Template list. Otherwise if selected but not needed there is not way to unselect.

**Comment by rminnett** [comment]
Ok, as we discussed, we need three changes:

1. Add a none option in the dropdown
2. When a user selects a template and then edits it, the dropdown should display "[NAME] (Unsaved)"
3. When the user saves an unsaved template, they should be able to rename it, but the original name is the default
