### ISSUE TITLE
Upon upload to private, the most recent upload is not displayed

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#111]
Upon upload to private, the most recent upload is not displayed, but if you upload another it appears.

**Comment by rminnett** [comment]
Is this only for uploads to new contributions, or updates, too? Does it show up if you refresh without uploading a second one?

**Comment by njarboe** [comment]
Just tried this again. Started with uploading a file link and then used this file:
[Jarboe2008Testing.txt](https://github.com/earthref/MagIC/files/1106212/Jarboe2008Testing.txt)
To upload to private space.
It did not appear in my private space even after reloading,
![screen shot 2017-06-27 at 10 16 36 am](https://user-images.githubusercontent.com/1278789/27600878-2b75f512-5b22-11e7-9b30-04a676edfef8.png)

**Comment by njarboe** [comment]
This seems to be associated with only the njarboe account and is now fixed with Rupert doing something on the backend.

**Comment by njarboe** [comment]
Happened again with my new account "Nicholas Jarboe - MagIC" (najmagic). Created a new contribution and uploaded it to my private workspace. Waited 5 min or so but did not appear:
![screen shot 2017-07-05 at 4 33 31 pm](https://user-images.githubusercontent.com/1278789/27889466-7ebfc1dc-61a1-11e7-959e-6a1b16371ec8.png)
Did a reload and it showed up.
![screen shot 2017-07-05 at 4 35 15 pm](https://user-images.githubusercontent.com/1278789/27889486-8e0eb4b8-61a1-11e7-81b6-fabea28087d9.png)

**Comment by njarboe** [comment]
Knowing that I needed to reload, I reloaded right away and my new contribution (Haile2017) did not show up. 
After a few minutes, still not showing up.
5 minutes later, still not showing up.

**Comment by rminnett** [comment]
It appears to only happen with larger contributions and also happens with other user accounts. I think the upload is getting interrupted by jumping to the private contributions list before the upload is complete. I’m deploying an update now, so I test it in a few minutes and see if that fixed it.

**Comment by rminnett** [comment]
The last update appears to have fixed it. Feel free to reopen the issue if not.
