### ISSUE TITLE
Round off errors in data model 2->3 conversion

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#112]
Some values end up with 15 decimal places but most don't for some reason. Need to keep the original number of sig digits. This is urgent if you want to start the data base from scratch to fix it or not so urgent if you can craw the current data store and fix them.

Examples below:

tab     ages
age     age_sigma       age_unit        citations       location        magnetic_reversal_chron method_codes    sample  site
16.72   0.105   Ma      This study      Pueblo Mountains        C5Cr    GM-ARAR-AP      03PM10C pm10
16.51   0.021   Ma      This study      Pueblo Mountains        C5Cn.2r GM-ARAR-SC-1050 03PMA   pma
16.72   0.14    Ma      This study      Summit Springs  C5Cn.3n GM-ARAR-AP      03SS02  ss02
17.14   0.18    Ma      This study      Summit Springs  C5Cn.3n GM-ARAR-AP      03SS09G-1       ss09
16.71   0.19    Ma      This study      Summit Springs  C5Cn.3n GM-ARAR-AP      03SS09G-2       ss09
9.81    0.011000000000000001    Ma      This study      Summit Springs  C5n.1n  GM-ARAR-SC-10   03SS17A-o       ss17
9.756   0.01    Ma      This study      Summit Springs  C5n.1n  GM-ARAR-SC-10   03SS17A-y       ss17
>>>>>>>>>>
tab     contribution
author  contributor     description     doi     id      magic_version   timestamp
@njarboe        @njarboe        Upgraded to MagIC Data Model 3.0 by the MagIC Database Team     10.1029/2008GC002067    12463   3.0     2011-07-19T09:28:14.000Z
>>>>>>>>>>
tab     locations
citations       continent_ocean country elevation_high  elevation_low   geological_province_sections    lat_n   lat_s   lithologies     location        location_type   lon_e   lon_w   region  scientists
This study      North America   United States   1795    1653.0  Columbia River Basalt Group     42.089  42.085  Basalt  Guano Rim       Stratigraphic Section   240.541 240.53400000000002      Oregon Plateau  Nicholas A. Jarboe
This study      North America   United States   1628    1308.5  Columbia River Basalt Group     42.77169        42.76763        Basalt  North Mickey    Stratigraphic Section   241.70432000000002      241.70202999999998      Oregon Plateau  Nicholas A. Jarboe
This study      North America   United States   2336    1343.0  Columbia River Basalt Group     42.06293        41.91142        Basalt  Pueblo Mountains        Stratigraphic Section   241.31400000000002      241.26377000000002      Oregon Plateau  Nicholas A. Jarboe
This study      North America   United States   1843    1540.0  Columbia River Basalt Group     43.11242        43.10825667     Basalt  Summit Springs  Stratigraphic Section   241.75512       241.72974       Oregon Plateau  Nicholas A. Jarboe
>>>>>>>>>>
tab     samples
citations       geologic_classes        geologic_types  lat     lithologies     lon     sample  site
This study      Igneous:Extrusive       Lava    41.96818        Basalt  241.28107999999997      03PM10C pm10
This study      Igneous:Extrusive       Lava    41.876999999999995      Basalt  241.248 03PMA   pma
This study      Igneous:Extrusive       Lava    43.11234        Basalt  241.73002999999997      03SS02  ss02
This study      Igneous:Extrusive       Lava    43.109190000000005      Basalt  241.73859       03SS09G-1       ss09
This study      Igneous:Extrusive       Lava    43.109190000000005      Basalt  241.73859       03SS09G-2       ss09
This study      Igneous:Extrusive       Lava    43.1108 Tuff    241.74917000000002      03SS17A-o       ss17
This study      Igneous:Extrusive       Lava    43.1108 Tuff    241.74917000000002      03SS17A-y       ss17

**Comment by njarboe** [comment]
Thinking over the importing from excel issue #127, I think we should not change values people give to the system. I will close that one. But in converting to 3.0 we should keep the same values that were given by the contributor in the upload.

**Comment by njarboe** [comment]
I don't think if we fix this in the future we can just change the values in every 2.5 to 3.0 version. If someone has downloaded a 3.0 version, they will expect it not to change (as they should) and discovering that the same labeled versions are not guaranteed to be the same would greatly hurt the reputation of an archiving repository. If we make changes we will need to make new versions (maybe only of the ones that have been downloaded?).

**Comment by rminnett** [comment]
You’re right, but we’re not currently tracking download statistics, although we should (new issue #135). Any changes to the latest activated versions should result in another new version being created with a contribution description explaining the change (issue #35). If there are any contributions with the rounding issue that have been updated since the automatic upgrade, they’ll have to be fixed manually.

**Comment by njarboe** [comment]
Lori and I have discussed this issue in PmagPy also. Our solution https://github.com/PmagPy/PmagPy/issues/511
At this moment still go be implemented.

**Comment by njarboe** [comment]
Now in batch mode changes #374
