### ISSUE TITLE
After clicking on the "Update Button", there is no option to select the data file to use

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#115]
After clicking on the "Update Button", there is no option to select the data file to use. The GUI just brings one to the private workspace with the most recent version as the new one.
I clicked to update Jarboe et al. 2008.
![screen shot 2017-06-26 at 9 27 01 pm](https://user-images.githubusercontent.com/1278789/27570966-104d61c8-5ab7-11e7-83ca-d60b48a9a0b3.png)
And the website then immediately when to this screen without the option to select the new data file. Maybe I just don't understand how to do it?
![screen shot 2017-06-26 at 9 29 06 pm](https://user-images.githubusercontent.com/1278789/27570988-39320152-5ab7-11e7-975c-54be9bd3a16e.png)

**Comment by rminnett** [comment]
Yes, it's not very clear yet - once you have the data from the current version in the private workspace, you can click "Upload" at the top to edit the data for one table or more and then select that contribution on the last step of the Upload tool.

**Comment by njarboe** [comment]
Private workspace does not seem to work at all now (Issue #119).

**Comment by njarboe** [comment]
This issue is about an older version of the software so I will close it and create new issues about this topic as needed.
