### ISSUE TITLE
When download the most recent version of Jarboe 2008 the MagIC Id of the file name does not match the one on the screen

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#117]
When download the most recent version of Jarboe 2008 the MagIC Id of the file name does not match the one on the screen. Download screen says MagIC Id 12463 while the save file name has ID 16223.
![screen shot 2017-06-26 at 9 37 52 pm](https://user-images.githubusercontent.com/1278789/27571235-1544f54a-5ab9-11e7-83ba-24785429a650.png)
![screen shot 2017-06-26 at 9 44 41 pm](https://user-images.githubusercontent.com/1278789/27571238-1803787e-5ab9-11e7-89df-e7b7671e5d63.png)

**Comment by rminnett** [comment]
This is related to #116. It was updating ID for the contribution (seen in the download), but not for indexing (seen in the search interface).
