### ISSUE TITLE
After clicking on update contribution and various steps, the private contribution list has both the activated contribution and the new private one

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#121]
Seeing two of the same contribution is confusing. After activating, this may be due to the fact that it looks like it thinks it is a different contribution and now there is a dup on the main page. Will add new issue for that problem.
![screen shot 2017-06-27 at 9 11 53 am](https://user-images.githubusercontent.com/1278789/27598094-4318787e-5b19-11e7-84a7-867718d2abbf.png)

**Comment by rminnett** [comment]
This should be resolved now.
