### ISSUE TITLE
Wondering why when downloading the " (1)" is added onto the name

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#123]
Wondering why when downloading the " (1)" is added onto the name. Is this added by the Chrome download wizard? For unix (and PmagPy) adding spaces to file names is a problem and () are also not usually used.

**Comment by rminnett** [comment]
If you already have a file by this name in your downloads folder, Chrome adds " (n)" to it to avoid overwriting the other file(s). Unless we add a timestamp or GUID to the filename to make it unique, there's not much we can do about this. The user just has to rename the file before using it.

**Comment by njarboe** [comment]
Was just making sure it was not something on our end. Thanks for the explanation. No changes needed.
