### ISSUE TITLE
Sprain's private contribution 2.5 MagIC file fails to upgrade

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#130]
Sprain's private contribution 2.5 MagIC file fails to upgrade with one error:

MagIC Data Model version 2.5 column "er_specimen_name" in table "rmag_hysteresis" is about to map value "BC0-3" into version 3.0 table "specimens", but column "specimen" already contains the value "N/A". undefined

I am not sure exactly what it means that the 'column "specimen" already contains the value "N/A". undefined"' so it is a bit hard to debug. Below is the magic file. If we can get this one working we can get a new contributor.

[magic_contribution_11047.txt](https://github.com/earthref/MagIC/files/1116472/magic_contribution_11047.txt)

**Comment by rminnett** [comment]
Here's the contribution without the "N/A" values.
[magic_contribution_11047.txt](https://github.com/earthref/MagIC/files/1120583/magic_contribution_11047.txt)
