### ISSUE TITLE
Download button not working in Private Contribution

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#140]
I guess if I can't reproduce it then best not to make an issue at all?
Download button not working in Private Contribution.
![screen shot 2017-07-05 at 5 08 17 pm](https://user-images.githubusercontent.com/1278789/27889945-972d0272-61a4-11e7-9c8b-f0b582eeeee8.png)

**Comment by rminnett** [comment]
I think the latest deployed version fixes this, but feel free to reopen the issue if you notice it again.
