### ISSUE TITLE
Year missing in Sprain et al. contribution. Should be 2015

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#145]
Year missing in Sprain et al. contribution. Should be 2015
![screen shot 2017-07-06 at 11 23 34 pm](https://user-images.githubusercontent.com/1278789/27945556-633f33be-62a2-11e7-8d86-a0f421249def.png)

**Comment by njarboe** [comment]
How did you test this fix Rupert. I still have this problem.
![screen shot 2017-07-10 at 9 52 58 am](https://user-images.githubusercontent.com/1278789/28029664-9e3dad64-6555-11e7-8791-4c0c129d60b9.png)

**Comment by rminnett** [comment]
The Crossref API is returning a published-online date instead of a published-print date for this DOI. I'll add a condition to fall back on the published-online date if the published-print date is not available.
