### ISSUE TITLE
v.5 and v.6 of Coble and Mahood (2016) have the same MagIC Id number of 16258

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#147]
v.5 and v.6 of Coble and Mahood (2016) have the same MagIC Id number of 16258. Not sure when this happened with all of my upload/download testing. I have downloaded v.6 so if you can just delete it and I will re-upload it. Or if it is easier make v.6 a different MagIC number.

![screen shot 2017-07-09 at 7 57 28 am](https://user-images.githubusercontent.com/1278789/27994999-4e6d3144-647c-11e7-8742-cfdce8c57715.png)

**Comment by njarboe** [comment]
Close this issue when the double MagIC number problem is fixed. Will make a new issue if the duplication happens again and I know what caused it.

**Comment by rminnett** [comment]
I set the latest ID to 16263.
