### ISSUE TITLE
Upload GUI says that I have one import error at the top but see no error to correct in the tables

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#151]
Upload GUI says that I have one import error at the top but see no error to correct in the tables. There are three warnings of tables with no rows but no errors displayed.
Excel file:
[Haile2017MagICUpload.xlsx](https://github.com/earthref/MagIC/files/1140071/Haile2017MagICUpload.xlsx)
ScreenShots:
![screen shot 2017-07-11 at 12 58 27 pm](https://user-images.githubusercontent.com/1278789/28088048-5d6ec87e-6639-11e7-8b59-b9bc0b55df3e.png)
![screen shot 2017-07-11 at 1 01 29 pm](https://user-images.githubusercontent.com/1278789/28088076-6d411ee6-6639-11e7-919e-ca5123ab188e.png)
![screen shot 2017-07-11 at 1 01 42 pm](https://user-images.githubusercontent.com/1278789/28088087-72255d00-6639-11e7-8bb0-2f97078fb0eb.png)
![screen shot 2017-07-11 at 1 01 57 pm](https://user-images.githubusercontent.com/1278789/28088092-781f617e-6639-11e7-97d2-13e8fa41f3ec.png)

**Comment by njarboe** [comment]
I thought the error might be due to the Number of Header Rows that are red, but I set them to zero and the red went away, but the error is still there.
![screen shot 2017-07-11 at 1 06 37 pm](https://user-images.githubusercontent.com/1278789/28088199-cdc40968-6639-11e7-8af5-4721f4fbdfbf.png)

**Comment by njarboe** [comment]
If I put some text in the empty Excel file then I can turn them off and the error goes away.
[Haile2017MagICUploadTest.xlsx](https://github.com/earthref/MagIC/files/1140092/Haile2017MagICUploadTest.xlsx)

**Comment by rminnett** [comment]
Fixed on live site
