### ISSUE TITLE
In the contribution titles, letters that go down are cut off. g's especially noticeable

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#155]
In the contribution titles, letters that go down are cut off. g's especially noticeable
![screen shot 2017-07-11 at 7 22 45 pm](https://user-images.githubusercontent.com/1278789/28099021-923ddcc2-666e-11e7-8cc2-11946f3dc6ea.png)

**Comment by rminnett** [comment]
#254 is a more updated version of this issue
