### ISSUE TITLE
Contribution summary shows 105 sites but 0 sites in site tab.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#180]
Contribution summary shows 105 sites but 0 sites in site tab.
![screen shot 2017-07-31 at 10 20 37 am](https://user-images.githubusercontent.com/1278789/28789419-36bea252-75da-11e7-86a4-85148d8d3762.png)

**Comment by rminnett** [comment]
This is an issue with the live site search. The beta site search already fixes this with the index all on all levels. The proposed solution to #182 also makes a contribution ID link to a search more robust by generating a `"id:12546" `search instead of a `"12546"` search on any field.
