### ISSUE TITLE
Need a search by author

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#182]
When I do a general search on jarboe and have the "Sort by Relevance" the second one on the list is one I contributed but otherwise am not associated with. Would be nice to have searches by First Author only and Author.
![screen shot 2017-07-31 at 10 57 52 am](https://user-images.githubusercontent.com/1278789/28790766-23628688-75df-11e7-9880-2f6181b0e449.png)

**Comment by rminnett** [comment]
I can relatively easily support an entry in the search bar like this:

`authors.family:"Jarboe"`

This makes use of the index structure and would allow other searches like:

`doi:"10.1016/0012-821x(93)90113"`

`method_codes:"DE-"`

I could make a popup when the search bar is focused with examples like we used to have.

**Comment by njarboe** [comment]
I think having access to this "advanced search" would be really great. Especially if it is not very hard. Maybe just put the three examples above in the greyed out search text after the examples you already have. We can set up a search help page with all the available indexes at some point.
