### ISSUE TITLE
Absolute Intensity Range should be changed to Intensity Range

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#185]
Absolute Intensity Range should be changed to Intensity Range
![screen shot 2017-07-31 at 11 04 41 am](https://user-images.githubusercontent.com/1278789/28791254-ba0d7c72-75e0-11e7-8aad-87d2dc9e8c17.png)

**Comment by rminnett** [comment]
And if a user later adds a range filter for relative intensity, that should be "Relative Intensity Range", though? Is "Intensity" commonly understood to be "Absolute Intensity" unless specifically "Relative Intensity"?

**Comment by njarboe** [comment]
Correct. Intensity is the default while relative would be specified.
