### ISSUE TITLE
Don't need list of number of parents and self (always 1) on summary page

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#190]
Don't need list of number of parents and self (always 1) on summary page.

**Comment by rminnett** [comment]
They don't appear to be very useful yet, but they'll become individual links to tabs in a popup that displays the raw contributed data. The "1 Location" on the Sites Summaries row will open the popup and show the location row, whereas the "1 Site" will show the site row. Once this is implemented, we can revisit whether those links are useful or not.

**Comment by njarboe** [comment]
Ok.
