### ISSUE TITLE
Group lower levels by the level above in summary table

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#191]
Group lower levels by the level above.
In this screen shot all of the sites in the "pacific ocean" location should be grouped.
![screen shot 2017-07-31 at 11 26 10 am](https://user-images.githubusercontent.com/1278789/28792232-c8744c34-75e3-11e7-8ef9-912ec9a2377e.png)

**Comment by rminnett** [comment]
I think we only want the "Rows" to be grouped by the level above, which should be implemented in that version on the beta page, I think the summaries should be 1 row per "thing" on the main tabs (i.e. one summary row per sample for the samples tab in your screen shot, which could be a summary over multiple sample rows for the same sample and includes information for associated parents and children in the hierarchy). Is there a better way of doing it?

**Comment by njarboe** [comment]
Ok. That seems fine. Just in row view.
