### ISSUE TITLE
0-11.7 ka age displays as -1950 YBP to 9.8 ka 

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#193]
0-11.7 ka age displays as -1950 YBP to 9.8 ka 

![screen shot 2017-07-31 at 11 51 03 am](https://user-images.githubusercontent.com/1278789/28793106-c62c2822-75e6-11e7-944b-80a15cacdf69.png)
![screen shot 2017-07-31 at 11 50 04 am](https://user-images.githubusercontent.com/1278789/28793108-c9cd8638-75e6-11e7-8d6a-d5f86dcba982.png)

**Comment by rminnett** [comment]
Display rules in #197 address this.
