### ISSUE TITLE
Default age for low ages should be AD/BC unless YBP is the units of all ages used in the summary.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#197]
Default age for low ages should be AD/BC unless YBP is the units of all ages used in the summary. Any age of 2000 AD should be displayed as 2000 AD not -50 YPB. The 1950 zero year will be very confusing to anyone not familiar with carbon dating. Use the max age units if ka, Ma, Ga.

**Comment by rminnett** [comment]
YBP is the default in the summary for small ages, but I can change that. At what point should it transition to ka (999.9 BC, 1 ka, 1.0001 ka, ...)?

**Comment by njarboe** [comment]
Use the unit of the oldest age used in the summary range for both the youngest and oldest ages. The only exception I can think of would be If the oldest age unit is YBP age and the youngest age is after 1950, use AD on the younger age (i.e, no negative ages displayed).

**Comment by rminnett** [comment]
Here are some proposed rules:

1. YBP is the fundamental unit, even if that's not what is displayed (i.e. 2000 YBP = 2 ka = -50 BC).
2. Always display AD for Age range min if <= 1950 YBP).
3. Age range max <= 1,950 YBP, use AD for min and max.
4. Age range max > 1,950 YBP and < 10,000 (8,050 BC), use BC for min and max.
5. Age range max >= 10,000 YBP and < 800,000, use ka for min and max.
6. Age range max >= 800,000 YBP and < 800,000,000, use Ma for min and max.
7. Age range max >= 800,000,000 YBP, use Ga for min and max.

Feel free to adjust any of those rules so I can implement them.

**Comment by njarboe** [comment]
Looking at the literature (10.1016/j.quascirev.2007.04.002,10.1016/j.quageo.2006.07.001) we should us BP instead of YBP for the abbreviation.

I was thinking that we might want to take the contributor's preferences into consideration when displaying the age, so proposed the previous rule. If it is a study based on Carbon dates and ages were provided in BP, that would be the age unit displayed. Maybe that is too hard to do and confusing. Using your rule list I would say:
1. Ok. minor typo. 2000 BP = 2 ka = 51 BC (actually 51 not 50. See below)
2. OK but <= 1949  Unfortunately the convention is 2 BC, 1 BC, 1 AD, 2 AD. No zero year.
3. 1950 BP is 1 BC so <= 1949
4. 8,000 (6,051 BC), use BC for min and max.
5. Age range max >= 8,000 BP and < 1,000,000, use ka for min and max.
6. Age range max >= 1,000,000 BP and < 1,000,000,000, use Ma for min and max.
7. Age range max >= 1,000,000,000 BP, use Ga for min and max.

**Comment by rminnett** [comment]
Good catch with the 1950 YBP = 1 BC. Anthony suggested an eighth rule to handle an edge case where the users probably meant a min of 0 and to avoid something like (1954 AD to 55 ka):

8. Age range max > 40 ka (roughly the radiocarbon limit) and min = 0 +/- 10 YBP, round min to 0 with the same unit as max.

Do you think displaying 900,000 YBP is better as 900 ka or 0.9 Ma? I'm not entirely convinced either way, but that's why I set the transition points at 800*.

**Comment by njarboe** [comment]
I personally like 0.9 Ma instead of 900 ka due to sig digits but 912 ka is
better than 0.912 Ma. SI guidelines and scientists in general use the
suffixes that jump three orders of magnitude and use the one that will
display between 1 and <1000.
