### ISSUE TITLE
Add missing suggested vocabularies

### ISSUE THREAD

**Issue by rminnett** [earthref/MagIC#20]
- [ ] instrument_codes
- [ ] astronomical_stage

**Comment by rminnett** [comment]
This query will retrieve all unique values and their frequency:

`GET magic_v2/_search
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "summary.contribution._is_latest": "true"
          }
        }
      ]
    }
  },
  "aggs": {
    "buckets": {
      "terms": {
        "field": "summary._all.instrument_codes.raw",
        "size": 10000
      }
    }
  }
}`

**Comment by njarboe** [comment]
Will separate this issue in two, one for each vocab list
