### ISSUE TITLE
Search filters should be in different order

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#202]
Not sure how the list is ordered at the moment but I would say something like:
Publication Author (need to add)
Publication Date (need to add)
Geologic Type
Geologic Class
Lithology
(Others alphabetically)
![screen shot 2017-08-14 at 3 56 31 pm](https://user-images.githubusercontent.com/1278789/29295684-93e65cbe-810a-11e7-85e8-7cda8994f599.png)

**Comment by rminnett** [comment]
It doesn't have a logical order yet, but I was planning to sort it based on where the columns are found in the data model, with any reference filters at the top.

**Comment by njarboe** [comment]
Sounds good.

**Comment by rminnett** [comment]
Overtaken by #516
