### ISSUE TITLE
Ages for a contribution should be displayed with the same units with range.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#203]
I think the age range would best be displayed with say 2.09-2.7 ka, 0-10 Ma, or 0-1.092 Ga.

Not sure where my list of rules went with gmail, github issues, skype, etc. 
Yours from email:
YBP is the fundamental unit, even if that's not what is displayed (i.e. 2000 YBP = 2 ka = -50 BC).
Always display AD for Age range min if <= 1950 YBP).
Age range max <= 1,950 YBP, use AD for min and max.
Age range max > 1,950 YBP and < 10,000 (8,050 BC), use BC for min and max.
Age range max >= 10,000 YBP and < 800,000, use ka for min and max.
Age range max >= 800,000 YBP and < 800,000,000, use Ma for min and max.
Age range max >= 800,000,000 YBP, use Ga for min and max.
Age range max > 40 ka (roughly the radiocarbon limit) and min = 0 +/- 10 YBP, round min to 0 with the same unit as max.

Modifying this I would say:

Use AD and BC for ages less than 6000 BC so display:
500-2001 AD
900 BC-412 AD
600-400 BC

If all the ages in the contribution are given in YBP then use that:
243-1000 YPB
950-13,200 YPB

Age range max >= 6,000 BC and < 1,000,000 YBP use ka for min and max. 2.65-689.23 ka
Age range max >= 800,000 YBP and < 1,000,000,000, use Ma for min and max. 5.8-34.2 Ma
Age range max >= 1,000,000,000 YBP, use Ga for min and max. 1.5-3.45 Ga
Age range max > 40 ka (roughly the radiocarbon limit) and min = 0 +/- 10 YBP, round min to 0 with the same unit as max.

This does not seem to be currently implemented
![screen shot 2017-08-14 at 5 43 24 pm](https://user-images.githubusercontent.com/1278789/29297774-1b46eae0-8118-11e7-99b2-0991c70ee3a9.png)
.

**Comment by rminnett** [comment]
Yes, I need to reindex the ages and then it should display properly. We can revisit the rules once the ages look more reasonable.

**Comment by rminnett** [comment]
The current version on the live site should address this.
