### ISSUE TITLE
PINT shows up twice on the External Database list

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#204]
PINT shows up twice on the External Database list.
![screen shot 2017-08-15 at 11 26 58 am](https://user-images.githubusercontent.com/1278789/29330049-d17b34b2-81ac-11e7-8f16-4e85e35b95e0.png)

**Comment by rminnett** [comment]
Yes, the PINT that is seen in 25 contributions is "PINT " with a space after it. "PINT" is seen in 161 contributions. The same happens with "PSVRL ". "PINT " is simply an example of a suggested vocabulary with "duplicate" spellings of the same term and should be cleaned up. If you expand the list of External Database filter buckets, most of the ones with 1 contribution need cleaning up (e.g. "GEOMAGIA57" should probably be "GEOMAGIA") and the ones that are integers or "length" are from a bug in an early version of the upgrade tool, which I'll clean up and reprocess.
