### ISSUE TITLE
Not clear what N stands for under the ages

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#205]
Not clear what N stands for under the ages.
![screen shot 2017-08-15 at 11 26 58 am](https://user-images.githubusercontent.com/1278789/29330391-e635b854-81ad-11e7-90ca-33c1b333f02e.png)

**Comment by rminnett** [comment]
Yes, the PINT that is seen in 25 contributions is "PINT " with a space after it. "PINT" is seen in 161 contributions. The same happens with "PSVRL ". "PINT " is simply an example of a suggested vocabulary with "duplicate" spellings of the same term and should be cleaned up. If you expand the list of External Database filter buckets, most of the ones with 1 contribution need cleaning up (e.g. "GEOMAGIA57" should probably be "GEOMAGIA") and the ones that are integers or "length" are from a bug in an early version of the upgrade tool, which I'll clean up and reprocess.

**Comment by njarboe** [comment]
In the Ben-Yosef et al. 2017 contribution N=444. The age table has 67 rows, there are 14 locations, and 67 sites. 444 seems to high in this case. Are they coming from specimens? They don't have ages.

**Comment by rminnett** [comment]
N is no longer displayed for ages.
