### ISSUE TITLE
Filtering seems to be an "or" not "and" when using multiple filters

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#207]
Filtering seems to be an "or" not "and" when using multiple filters. 
In the below see the Cai et al. 2017 that has a max age of 6.45 ka and a filter set for ages 1 to 5 Ma.

![screen shot 2017-08-15 at 1 38 15 pm](https://user-images.githubusercontent.com/1278789/29335313-17f2e234-81bf-11e7-9310-153444382310.png)

**Comment by rminnett** [comment]
What you're seeing is that the range filters are matching intersections, not inclusions. If you filter 1-5 Ma, do you expect to see a contribution with ages of 4-6 Ma, or only one with ages of 2-4 Ma? Similarly with intensities and any other numeric range filter?

**Comment by njarboe** [comment]
If I filter 1-5 Ma, I don't expect to see the Cai et al. 2017 that has a max age of 6.45 ka as I stated above. Not sure how this fits into what you are saying.

**Comment by rminnett** [comment]
Ah, I see, I just deployed a patch to see if it fixes this. Refresh and see if it behaves the way you expect.

**Comment by njarboe** [comment]
Looks good an beta.
