### ISSUE TITLE
Sometimes typing in data in search or filters does not activate a new search

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#208]
Sometimes typing in data in search or filters does not activate a new search. Can't always cause this to happen. Happens about 20% of the time.

**Comment by rminnett** [comment]
This might have been related to the patch I just deployed. Prior to that, editing the range filters might have stopped the searching from working until the page was refreshed. If you notice it starting to behave strangely again, please take a screenshot of the developer console.
