### ISSUE TITLE
Add publication author and publication date and/or range to search filters

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#209]
Add publication author and publication date and/or range to search filters. I believe we wanted these in the minimum search product.

**Comment by rminnett** [comment]
#179 called for sorting by author and publication, but I can add filtering, too. For the time being, we only have reference years, but I have a note to retrieve timestamps for more precise sorting and filtering. The author filter will also need a new index mapping to store the first and last name of each author together for aggregation.

**Comment by njarboe** [comment]
For a future search iteration then.

**Comment by rminnett** [comment]
Author text filter and publication year range filter are on the live site now.
