### ISSUE TITLE
Ages better displayed as a range. Switch min/max age for AD/BC

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#211]
Ages better displayed as a range, especially for AD/BC. So display Age: 1013-1585 AD or 0.45-4.95 ka. In the first case you will have max age-min age and in the second min age-max age. From issue #203:

Use AD and BC for ages less than 6000 BC so display:
500-2001 AD
900 BC-412 AD
600-400 BC

**Comment by rminnett** [comment]
The current version on the live site should address this.
