### ISSUE TITLE
Uploading is disabled

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#216]
Uploading is impossible. No message informing users.

![screen shot 2017-08-28 at 9 39 18 am](https://user-images.githubusercontent.com/1278789/29783333-d8584d2e-8bd4-11e7-902e-f20d80be45e5.png)
[magic_contribution_11929.txt](https://github.com/earthref/MagIC/files/1257532/magic_contribution_11929.txt)

**Comment by rminnett** [comment]
There is a temporary message for now.

**Comment by rminnett** [comment]
Uploading and activating are enabled on the live site.
