### ISSUE TITLE
Clicking on link to a single contribution does not work

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#217]
Clicking on link to a single contribution does not work. Goes to a page with No Items to Display. The search bar ends up with text like "?q=16263"
<img width="1290" alt="screen shot 2017-08-28 at 12 49 22 pm" src="https://user-images.githubusercontent.com/1278789/29790790-be83b760-8bef-11e7-92b5-5142b98d082b.png">
<img width="1289" alt="screen shot 2017-08-28 at 12 49 43 pm" src="https://user-images.githubusercontent.com/1278789/29790794-c0f7e43a-8bef-11e7-9661-92d95b10ef0a.png">

**Comment by rminnett** [comment]
Fixed, thanks!
