### ISSUE TITLE
Fleck 2014 shows v2 as the current data version but only v1 in download list

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#230]
Fleck 2014 shows v2 as the current data version but only v1 in download list.
![screen shot 2017-09-19 at 3 47 08 pm](https://user-images.githubusercontent.com/1278789/30619018-f6b6cc80-9d51-11e7-8631-6c2bf2393e82.png)

**Comment by rminnett** [comment]
Fixed in ES
