### ISSUE TITLE
Diskette icon button used for "activate DOI lookup" action not clear

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#234]
Diskette icon button used for "activate DOI lookup" action not clear. Maybe the red DOI label can cause the lookup. In addition, the label that says "search" or "enter" where the icon is could work. To many custom icons used these days and not needed with the big screen of a desktop.
![screen shot 2017-09-20 at 7 24 18 pm](https://user-images.githubusercontent.com/1278789/30676264-071fad60-9e3a-11e7-88da-a9b6169447b0.png)

**Comment by rminnett** [comment]
I'll change this to a "Save" on the right that looks like the "DOI" label on the left.

**Comment by rminnett** [comment]
Save on blur or "Enter" if changed and show a warning if no DOI is found
