### ISSUE TITLE
Download in private workspace downloads file with "[object Object]" as the content 

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#235]
Big button downloads a file with the text "[object Object]" in it.

![screen shot 2017-09-20 at 7 56 24 pm](https://user-images.githubusercontent.com/1278789/30676976-e32658ce-9e3d-11e7-8f52-5e81d2868fda.png)

Downloaded file:
[magic_contribution_16291.txt](https://github.com/earthref/MagIC/files/1319844/magic_contribution_16291.txt)

**Comment by rminnett** [comment]
Fixed on the beta site.
