### ISSUE TITLE
When Importing an Excel file the Parse As displays "MagIC Text File"

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#237]
The software guesses it is an Excel file and parses correctly but does not change the pulldown to "Excel file"

<img width="1263" alt="screen shot 2017-09-21 at 10 49 52 am" src="https://user-images.githubusercontent.com/1278789/30710759-68e877c6-9ebb-11e7-9990-714fc53917c3.png">
[BoringForMagIC.xlsx](https://github.com/earthref/MagIC/files/1322272/BoringForMagIC.xlsx)

**Comment by rminnett** [comment]
Fixed on the live site.
