### ISSUE TITLE
Cannot save the import template after making changes

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#238]
The Save Changes button does not turn on when a change is made in the import template.
![screen shot 2017-09-21 at 11 23 54 am](https://user-images.githubusercontent.com/1278789/30712105-ad669f32-9ebf-11e7-9fbf-09406ba63d68.png)

**Comment by rminnett** [comment]
If you're creating a new one, you click "Create New". If you have one loaded and then make changes, you should be able to save.

Perhaps that's not clear. Is it better if I hide the "Save Changes" button if one isn't loaded? I'll also add a "Default Template" option in the pull down to revert the changes.

**Comment by njarboe** [comment]
Sorry. Messed up the screen shot. It should be clear when it is working. Here is a shot with the Save Changes grey when the Template is set.
![screen shot 2017-09-21 at 4 57 11 pm](https://user-images.githubusercontent.com/1278789/30723737-12fe7332-9eee-11e7-9936-74e613175011.png)

**Comment by njarboe** [comment]
I think there should just be one template for the whole file, not each table individually. People won't want to select the template for each table. It will seem like extra work especially if you have locations through measurements. Saving seems fine. I'll make a new issue about having the template for all the tables.
