### ISSUE TITLE
Change text "Upload to This Study" to "Add Data to This Study" 

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#240]
I can do this and want to do this (I know it is trivial for you to change it) Rupert after you push the changes to github and I can pull them. I would like to learn how to update the server so I can make changes myself and git them on the live site.
 
Change text "Upload to This Study" to "Add Data to This Study" 
![screen shot 2017-09-21 at 11 49 38 am](https://user-images.githubusercontent.com/1278789/30713135-23e301e8-9ec3-11e7-9e44-5ad8dd5b3809.png)

**Comment by rminnett** [comment]
Fixed on the live site.
