### ISSUE TITLE
Remove link from the MagIC Contribution Link as the link does not work before activation

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#241]
Remove link from the MagIC Contribution Link as the link does not work before activation.

![screen shot 2017-09-21 at 11 57 16 am](https://user-images.githubusercontent.com/1278789/30713426-10cf286a-9ec4-11e7-8a2c-ef3da413c336.png)

**Comment by rminnett** [comment]
Fixed on beta and live sites.
