### ISSUE TITLE
Change delete warning to "Warning! You cannot undo this delete."

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#242]
"irreversible" does not seem to be the right word. If I re-upload the same data I have reversed the delete.
![screen shot 2017-09-21 at 4 08 46 pm](https://user-images.githubusercontent.com/1278789/30722694-7b5d3514-9ee7-11e7-9f6b-c8a2dcb58a13.png)

**Comment by rminnett** [comment]
Fixed on beta.
