### ISSUE TITLE
Change "Describe the changes being made in this version" 

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#243]
Change "Describe the changes being made in this version"  to "Top level information about this upload".

This makes more sense but I think it would be even better to put the previous versions description in as the default text unless specified in the contribution table. That way the description propagates through version unless someone changes it on purpose. People can add or delete as they will. 

Having the text propagate is a bit harder than changing the text in the box so I'll change the text in the box and then create a new issue about propagating the description at that time.

![screen shot 2017-09-21 at 4 21 12 pm](https://user-images.githubusercontent.com/1278789/30722973-ed421d42-9ee8-11e7-926e-6da347fc5649.png)

**Comment by njarboe** [comment]
When I created this issue I thought the description field would be used for describing the dataset when uploading, so that one should have all the descriptions on the top level. But now I see that what the description field is used for; describing the changes in each version. The data is described in the journal paper and the format of the data itself. Sorry about the mix up and if you would set the description to default to blank, that would be great.

**Comment by njarboe** [comment]
Not blank. But like we had before "Describe the changes being made in this version" in the grey font.

**Comment by rminnett** [comment]
Ok, thanks - I think this can close then because the default text is already "Describe the changes being made in this version":

![image](https://user-images.githubusercontent.com/1182698/78829118-a5b13500-799a-11ea-85c4-2d3abb0abde4.png)
