### ISSUE TITLE
Can't add additional table to private contribution

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#25]
Created a private contribution with a location table. Started the upload process again with a sites table and when I tried to add this table to the "Nick test" contribution I got a 500 error. Looks like it is try to upload to "My contribution" not "Nick test".

<img width="865" alt="screen shot 2017-02-01 at 4 54 22 pm" src="https://cloud.githubusercontent.com/assets/1278789/22532879/31690d7e-e89f-11e6-8665-9a64729380f6.png">

**Comment by rminnett** [comment]
According to the server logs, it appears to have lost track that you were logged in. I'll try to recreate this and add some more descriptive error messages.

**Comment by njarboe** [comment]
I logged out and logged back in again. Tried to upload a table to the same
existing private contribution and got the same error.

**Comment by njarboe** [comment]
Still seems to fail. On Chrome. Maybe related to the fact that I have set the "Upload to" to Nick test and it is trying to upload to "My Contribution" Still error: 500.

<img width="877" alt="screen shot 2017-02-04 at 12 57 31 pm" src="https://cloud.githubusercontent.com/assets/1278789/22621471/8711dd5a-ead9-11e6-852a-64441eada082.png">

**Comment by rminnett** [comment]
Sorry, looks like the latest update to the website didn't include that commit. It should be working now.
