### ISSUE TITLE
Text when activating ("Warning! You cannot undo this delete.") is wrong

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#250]
Text when activating ("Warning! You cannot undo this delete.") is wrong
![screen shot 2017-09-22 at 11 19 30 am](https://user-images.githubusercontent.com/1278789/30758640-13b6fb24-9f88-11e7-9f95-6d06385042f6.png)

**Comment by rminnett** [comment]
Fixed on the live site.
