### ISSUE TITLE
Data DOI should be text until the link works. Change label to say "Future Data DOI Link"

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#251]
Data DOI should be a link until the link works. Change text to say "Future Data DOI Link"

![screen shot 2017-09-22 at 11 24 20 am](https://user-images.githubusercontent.com/1278789/30758776-9ab3c9ae-9f88-11e7-89f9-d77495584c1c.png)

**Comment by rminnett** [comment]
How about "Data DOI Queued for Creation" to emphasize the fact that we're working on it?

**Comment by rminnett** [comment]
Fixed on live site.

**Comment by njarboe** [comment]
looks good
