### ISSUE TITLE
Problem with version number when trying to update Sprain 2016

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#256]
I'm trying to update the Sprain 2016 contribution. I am not the owner, so I don't know if that is a problem but the current version is 1 and when I uploaded a modified magic text file it shows up as version 11. I activated the contribution at it say v. 11
[magic_contribution_16281Modified.txt](https://github.com/earthref/MagIC/files/1325953/magic_contribution_16281Modified.txt)
![screen shot 2017-09-22 at 2 57 22 pm](https://user-images.githubusercontent.com/1278789/30765827-62e79e7e-9fa6-11e7-8cb3-07c7507004e0.png)
![screen shot 2017-09-22 at 2 59 56 pm](https://user-images.githubusercontent.com/1278789/30765902-b724dc2c-9fa6-11e7-8aba-f72cd272810d.png)

**Comment by rminnett** [comment]
Change version from 11 to 2 in ES. Fixed on live and beta sites so future uploads don't do this.
