### ISSUE TITLE
Error on trying to upload file for Sprain 2016

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#258]
Went through upload sequence and when try to put into the private workspace I got this error:
<img width="1070" alt="screen shot 2017-09-23 at 12 57 37 am" src="https://user-images.githubusercontent.com/1278789/30771346-b0e6bd5e-9ffa-11e7-976c-5667ea9fd06a.png">

With this file:
[magic_contribution_16281Modified.txt](https://github.com/earthref/MagIC/files/1326376/magic_contribution_16281Modified.txt)

**Comment by rminnett** [comment]
Fixed on the live site.

**Comment by njarboe** [comment]
thanks
