### ISSUE TITLE
Uploading to an existing contribution has an error

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#265]
Uploading to an existing contribution has an error.
[magic_contribution_16307Mod.txt](https://github.com/earthref/MagIC/files/1345871/magic_contribution_16307Mod.txt)
![screen shot 2017-09-29 at 4 16 01 pm](https://user-images.githubusercontent.com/1278789/31039317-af78f874-a531-11e7-9288-ec4025cc4c93.png)

**Comment by rminnett** [comment]
Ok, I'll fix this tonight
