### ISSUE TITLE
Need moving circle to show activation is in progress after hitting activate button

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#267]
Need moving circle to show activation is in progress after hitting activate button. It can take many seconds to activate so a "computer is doing something, please wait" icon is needed.
![screen shot 2017-09-29 at 4 22 22 pm](https://user-images.githubusercontent.com/1278789/31039457-a9e9dfa8-a532-11e7-87c1-d80b14e5cb87.png)

**Comment by rminnett** [comment]
Will be addressed with #427
