### ISSUE TITLE
age_low means age_younger and age_high means age older. Need to check and fix all database entries

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#275]
Age low and age high are not clear terms. age_low means age younger and age_high means age older. Need to check and fix all database entries.

Some description on the error:
Age younger and older would have been much better but I think we are stuck with this ambiguous wording. I can change the descriptions to be clear at least, but we have used them inconsistently in the database. For old ages, ie 175-185 Ma, the higher number has been put in the age_high column i.e. 185. This is from GPMDB MagIC contribution 13434.

age_low	age_high	age_unit
		
175	185	Ma

This is how I understood the meaning also, but I don't work with calendar year dates where it seems funny to say age_high is 1200AD and age_low is 1750AD

I set up the ages in Cromwell's Hawaii data with this age convention and "Create MagIC file for upload" gives the error message on the location table - according to the above convention "Create MagIC file for upload" is checking and rejecting the correct convention.
name	row_number	problem_type	problem_col	error_message
Hawaii	0	value	age_high	1843 (age_high) must be >= 2010 (age_low)
Hawaii	0	value	age_low	2010 (age_low) must be <= 1843 (age_high)

Ron's Shaar 2017 contribution  13949 also has this age inversion problem problem
age_low	age_high	age_unit
1400	1500	Years Cal AD (+/-)

so we were not checking this on Dec 12, 2016

I checked one of Ron's older contributions (Dec 31,2014), 12116, and it also has the incorrect age on the sites, although he is missing ages in the location table.

age	 age_low	age_high	age_unit
-918	 -930        -913	        Years Cal AD (+/-)

so I'm not sure if the was ever checked in the old workbook system.

**Comment by rminnett** [comment]
Ah, ok, so there are two paths we can take:

1. **Age Low/High are bounds in either order:**
    - Remove the validation requirement in the data model that age_low <= age_high.
    - Relax the summarizing so Elasticsearch will still index (1400 AD to 1500 AD) as (450 BP to 550 BP) and not ignore (550 BP to 450 BP).
    - Re-index existing data.

2. **Age Low (BP) <= Age High (BP):**
    - Implement the validation requirement that age_low (in BP) <= age_high (in BP), which is confusing if the age_unit is Years AD.
    - Fix all of the contributions that don't satisfy this.

I vote for 1. to avoid updating lots of existing contributions and to handle future misinterpretations of age_low/age_high, but I don't know if this causes problems with PmagPy or other software that expect age_low/age_high to be in a certain order?

**Comment by njarboe** [comment]
I have changed to google doc description of ages to:

age_low | Inferred Age Low | Location inferred age, Low range, Can be either oldest or youngest age
age_high | Inferred Age High | Location inferred age, High range, Can be either oldest or youngest age
