### ISSUE TITLE
Can activate when DOI is not set

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#276]
Can activate when DOI is not set.

<img width="1050" alt="screen shot 2017-10-02 at 5 14 08 pm" src="https://user-images.githubusercontent.com/1278789/31089889-3d8f33d4-a795-11e7-8622-0ab52a0422b7.png">

If you could delete this on the live site that would be great.

**Comment by rminnett** [comment]
Deleted 16312, I'll see why it's not checking for a DOI at activation.
