### ISSUE TITLE
Failed to create a new contribution with name "DArgella-Filho2008"

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#281]
Failed to create a new contribution with name "DArgella-Filho2008". Other names also fail.

<img width="1110" alt="screen shot 2017-10-03 at 5 12 53 pm" src="https://user-images.githubusercontent.com/1278789/31138523-536a2fd2-a85e-11e7-85e1-68da96d98a7f.png">

**Comment by rminnett** [comment]
ES had a bad contribution ID, blocking the next contribution

**Comment by njarboe** [comment]
Happened again.
<img width="1405" alt="screen shot 2017-10-03 at 10 45 03 pm" src="https://user-images.githubusercontent.com/1278789/31152714-d5aa959e-a88c-11e7-82d5-65ecf8c95a2e.png">

**Comment by njarboe** [comment]
Fixed at the moment
