### ISSUE TITLE
Some recent contributions still not indexed on lower levels

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#287]
Some recent contributions still not indexed on lower levels. For example:
<img width="1278" alt="screen shot 2017-10-05 at 12 57 04 pm" src="https://user-images.githubusercontent.com/1278789/31228384-dbe70460-a9cc-11e7-94c2-a6e665ca98ab.png">

**Comment by rminnett** [comment]
Data quality unit tests should uncover contributions like this so we can address them (#302)
