### ISSUE TITLE
Map has extra spot not in data file

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#292]
The Greve et al 2016 has a spot in Africa that I don't see in the data file and should not be there.
![screen shot 2017-10-23 at 4 28 51 pm](https://user-images.githubusercontent.com/1278789/31918050-78f8c5f4-b80f-11e7-8965-25a9a95e35e7.png)

It also has not been indexed to see the lower levels.

**Comment by rminnett** [comment]
I suspect these (lat=1, lon=1) entries are the source of that African data point:

![image](https://user-images.githubusercontent.com/1182698/31925223-22bc1e52-b83c-11e7-91c4-260017d8d147.png)

**Comment by njarboe** [comment]
Ok, missed that. Sorry about wasting your time. Data entry problem.

**Comment by njarboe** [comment]
Although on closer inspection the above file is from Greve et al 2016 not Greve and Turner 2017. But the both have the same problem in the data.
