### ISSUE TITLE
When only one contribution is found in a search, default to the contribution view.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#293]
Greve & Turner has not been indexed to show lower levels. Maybe other exist?

![screen shot 2017-10-23 at 4 32 38 pm](https://user-images.githubusercontent.com/1278789/31918111-d10f5154-b80f-11e7-9df3-b56f0cff461e.png)

**Comment by njarboe** [comment]
This is because even when the search returns a single contribution it does not go the the same view as the contribution link. What are the other levels at the top for in this view? Will change this issue to describe the UI problem.

**Comment by rminnett** [comment]
I think this is working as intended. Navigating to a contribution by following a contribution ID link (e.g. https://earthref.org/MagIC/16814) will display the Contributions tab, even if you're currently on a different tab. I don't think that editing the text search field, even if it results in matching only one contribution (as 'id:"16302"', or 'New and revised palaeomagnetic secular variation records from post-glacial volcanic materials in New Zealand' does) should change the current tab. This does become an issue if the contribution is not fully indexed, but then searching and filtering is not fully functional for that contribution yet and we shouldn't make UI changes for a situation that resolves itself once the indexing completes.

**Comment by njarboe** [comment]
Ok.
