### ISSUE TITLE
File cannot be uploaded because it has an error but no error listed to fix

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#294]
File cannot be uploaded because it has an error but no error listed to fix.
<rant> .txt added to end of this .csv file because of stupid GitHub file upload restrictions. Can you tell me why one would restrict what the filename can be for uploading to a GitHub issue? If I know why, it might not be so frustrating. A quick google did not work for me. </rant>

[Ref1.csv.txt](https://github.com/earthref/MagIC/files/1412729/Ref1.csv.txt)
![screen shot 2017-10-24 at 3 38 28 pm](https://user-images.githubusercontent.com/1278789/31971857-93d96338-b8d2-11e7-9af5-4f34fefcbcba.png)

**Comment by rminnett** [comment]
Fixed on the live site. Let me know if there are any more issues.

![image](https://user-images.githubusercontent.com/1182698/32022879-8d71facc-b98c-11e7-9d0a-19227b88f424.png)
