### ISSUE TITLE
Remove whitespace between bottom of search results and the footer.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#30]
Seeing more data would be good.

**Comment by rminnett** [comment]
Do you mean this whitespace outlined in red:

![image](https://cloud.githubusercontent.com/assets/1182698/22609648/e2f2d98a-ea16-11e6-90f3-86466791a7c0.png)

**Comment by njarboe** [comment]
Yes. Maybe it is good for looks but it would be nice to have a scientist user mode (condensed mode, like the gmail option). I'll open that as another issue.
