### ISSUE TITLE
Cottrell & Tarduno 1999 has error when I try to look at the site level data

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#300]
Cottrell & Tarduno 1999 has error when I try to look at the site level data. 
https://www2.earthref.org/MagIC/13239

![screen shot 2017-11-10 at 11 39 05 am](https://user-images.githubusercontent.com/1278789/32675575-2c0b914e-c60c-11e7-9074-70dfe641aedf.png)

**Comment by rminnett** [comment]
Can you try again, please? It looks like it just timed out on the request from Meteor to ElasticSearch because ElasticSearch was busy finishing previous requests. I'll try increasing the queue length and timeout in the meantime.

**Comment by njarboe** [comment]
Working now. Thanks.
