### ISSUE TITLE
Make vocabulary filter statistics consistent as they change

### ISSUE THREAD

**Issue by rminnett** [earthref/MagIC#313]
@moonshoes87 reported inconsistencies in the filter aggregate statistics. Investigate this workflow:

- earthref.org/MagIC/search
- expand "Software Package" filter
- check "pmagpy-3.4.0" and note 5 contributions now match it
- check "pmagpy-3.2.1" and note 4 contributions now match it, although it was 1 before checking it

**Comment by rminnett** [comment]
I think this comes from the statistics using an "AND" operation and the results using an "OR" operation. When checking "pmagpy-3.4.0", there are 5 contributions shown, of which 1 also has "pmagpy-3.2.1". When also checking "pmagpy-3.2.1", there are now 8 contributions shown, of which 4 have "pmagpy-3.2.1" and 5 have "pmagpy-3.4.0" and 1 has both. I'll change the logic for calculating the statistics to use an "OR" operation.

**Comment by moonshoes87** [comment]
I was just looking at this again and got some results I wasn't expecting.  When I select one filtering option, the list narrows to include only other items that co-occur with my selected option.  In some cases, that means the rest of the list disappears:
<img width="296" alt="screen shot 2018-03-28 at 11 45 51 am" src="https://user-images.githubusercontent.com/1836578/38049866-29f8d6b2-327e-11e8-860c-f9681da428de.png">

Is there a way in the UI to search for records with pmagpy-3.0 or pmagpy-3.1?  Or is that not a preferred behavior?

**Comment by rminnett** [comment]
This should behave the way you expected now - let me know if it doesn't and I can reopen the issue.
