### ISSUE TITLE
Fix upgrade tool so 2.5 measurement.number is properly mapped to measurement.measurement and measurement.treat_step_num

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#317]
Fix upgrade tool so 2.5 measurement.number is properly mapped to measurement.measurement and measurement.treat_step_num.

For 2.5 files where measurement.number is an int <1000, map measurement.number to measurement.treat_step_num and map 2.5 measurement.magic_experiment_name + "_" +measurement.number to measurement.measurement. 

otherwise map measurement.number to measurement.measurement

**Comment by njarboe** [comment]
added example files from Lisa.
2.5:
[magic_measurements.txt](https://github.com/earthref/MagIC/files/1798607/magic_measurements.txt)
3.0 run through upgrade tool, not working in Thellier GUI:
[measurements.txt](https://github.com/earthref/MagIC/files/1798608/measurements.txt)

**Comment by moonshoes87** [comment]
Great.  Also, as of the commits below, Thellier GUI does this same mapping internally.  

https://github.com/PmagPy/PmagPy/commit/49bf27e271e8bbd4e2b668990ee7b75e0f75349f

https://github.com/PmagPy/PmagPy/commit/cc7457a350f36e520314fb8d35f9ac63da450e23
