### ISSUE TITLE
Create condensed mode for search to see more data at once

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#32]
It might be nice to have a condensed mode, especially people with smaller screens (like most laptops). Maybe remove the "Magnetic Information Consortium" text and logo near the top, reduce the whitespace around many of the boxes to near zero, and remove the footer. Not sure if this mode flag should be reset when re-visiting the search page or set permanently by the user.

**Comment by rminnett** [comment]
Overtaken by #433
