### ISSUE TITLE
MagIC Database Team link on data models page broken

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#321]
MagIC Database Team link on data models page broken
![screen shot 2018-03-13 at 2 41 03 pm](https://user-images.githubusercontent.com/1278789/37371438-a2770cac-26cc-11e8-9e03-9cfdd1bd99ad.png)
![screen shot 2018-03-13 at 2 41 56 pm](https://user-images.githubusercontent.com/1278789/37371487-bee2c9ee-26cc-11e8-9fd8-b6bb3c96e1cd.png)

**Comment by rminnett** [comment]
Text has been removed.
