### ISSUE TITLE
Contribution with 84 locations and 2474 sites never completes uploading to private contribution

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#328]
Contribution with 84 locations and 2474 sites never completes uploading to private contribution. After  hitting upload on the first upload page it takes about two minutes to process and on Chrome I get this message:
![screen shot 2018-03-22 at 3 43 05 pm](https://user-images.githubusercontent.com/1278789/37802882-78dfd238-2de9-11e8-8cde-9c6b7cb35d37.png)
It would be nice not to get this message, but if I hit wait then in about a minute I get the next page. I enter the name for the upload and then click through. 
![screen shot 2018-03-22 at 3 52 06 pm](https://user-images.githubusercontent.com/1278789/37802934-abd168fa-2de9-11e8-9828-618b34a4e6af.png)
After 15 minutes the page is still spinning. 
If I click back to the homepage at this point it looks like the server is hung still as the recent contributions do not load. After a bit a reload loads the whole page. 

If I then go to my private contributions, it looks like it fully loaded (have not checked the data in detail) but then got hung up. 
I created this magic file by uploading an excel file with the same data and then downloading the magic file. When uploading using excel, I had the same problems as above.

[magic_contribution_16429.txt](https://github.com/earthref/MagIC/files/1839545/magic_contribution_16429.txt)

**Comment by rminnett** [comment]
Yes, I can see in the server logs that it was using too many resources inserting the data into Elasticsearch. I'll see if I can recreate this locally and fix it.

**Comment by rminnett** [comment]
This should upload more easily now - feel free to reopen the issue if you have more trouble.
