### ISSUE TITLE
File upload fails for all files

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#334]
File upload fails for all files. Mireille and I both get an error when trying to upload.

<img width="1123" alt="screen shot 2018-04-11 at 4 37 03 am" src="https://user-images.githubusercontent.com/1278789/38614515-4ea58dce-3d42-11e8-9bf6-2e355870a333.png">

Here is the file I used to try and upload to my private workspace:
[ExcelFormulaExamplesFleck2014.xlsx](https://github.com/earthref/MagIC/files/1898619/ExcelFormulaExamplesFleck2014.xlsx)
I set the first table to locations and turn off the two extra columns in the second table.

**Comment by rminnett** [comment]
Ok, I'll take a look at this later today.
