### ISSUE TITLE
Author list missing for most recent Cromwell contribution

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#337]
Author list missing for most recent Cromwell contribution. DOI:10.1002/2017GC007318
The doi link is live. Not sure why the author list is not returned.

**Comment by rminnett** [comment]
This is an issue with the "author" data missing from the CrossRef metadata:

https://api.crossref.org/works/10.1002/2017GC007318

Compared to: 

https://api.crossref.org/works/10.1139/e77-103

I've noticed this on another contribution - sometimes the links above return with the author data and sometimes without. I'll try to re-index it with the authors...

**Comment by njarboe** [comment]
Stuart Gilder uploaded some data when I was in Munich that also has this problem of no Authors. DOI:10.1016/S0012-821X(03)00102-X

**Comment by rminnett** [comment]
Yes, I see. I fixed those two and wrote a unit test that can quickly fix other ones that have issues with the CrossRef metadata in the future. I'm not sure why the metadata from CrossRef sometimes doesn't include the authors, though.
