### ISSUE TITLE
Upgrading a 2.5 measurement file to 3.0 can create an empty location table

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#339]
I tried upgrading a 2.5 contribution and I got these lines in the downloaded file:

    >>>>>>>>>>
    tab delimited   locations
    >>>>>>>>>>

I believe this bug is caused by generating specimen/sample/site/location tables from upgrading measurement files.  In this case, presumably no locations could be found.  This caused some things to break in PmagPy.  I'm fixing those, but this might be worth fixing in MagIC as well?

**Comment by rminnett** [comment]
If it isn't too much trouble to fix those in PmagPy, I think it's ok like this for the upgrade tool. Afterall, this is still a valid MagIC text file with not locations data, so we should be able to handle this.
