### ISSUE TITLE
Strange email sent when creating a new user account using Windows and Thunderbird

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#340]
Michael Wack at LMU (Ludwig Maximillian University in Munich) created a new user and got this strange email (I included his comment on it):

Betreff: | EarthRef.org Address Book -- Notification
-- | --
Wed, 18 Apr 2018 05:11:34 -0700
akoppers@gmail.com
wack@geophysik.uni-muenchen.de
ClRoYW5rIHlvdSAuLi4KCllvdXIgYWRkcmVzcyBpbmZvcm1hdGlvbiBoYXMgYmVlbiBhZGRlZCB0
byB0aGUgaHR0cDovL2VhcnRocmVmLm9yZyBvbmxpbmUgZGF0YWJhc2VzLgpBdCBhbnkgdGltZSB5
b3UgY2FuIGVkaXQgeW91ciBpbmZvcm1hdGlvbiBieSBmb2xsb3dpbmcgdGhlIFVSTCBiZWxvdyAu
Li4KCgkgaHR0cHM6Ly9lYXJ0aHJlZi5vcmcvY2dpLWJpbi9lcm1sLmNnaT9uPTg1NTkKCgkgVXNl
cm5hbWUgOiBtd2FjayAgCgpGb3IgZnVydGhlciBpbmZvcm1hdGlvbiBjb250YWN0IHVzIHVzaW5n
IHRoZSBlbWFpbCBhZGRyZXNzIGJlbG93IC4uLgoKPT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKRHIu
IEFudGhvbnkgQS5QLiBLb3BwZXJzCkFzc29jaWF0ZSBQcm9mZXNzb3Igb2YgTWFyaW5lIEdlb2xv
Z3kgYW5kIEdlb3BoeXNpY3MKQ29sbGVnZSBvZiBFYXJ0aCwgT2NlYW4gYW5kIEF0bW9zcGhlcmlj
IFNjaWVuY2VzCk9yZWdvbiBTdGF0ZSBVbml2ZXJzaXR5CjEwNCBDT0FTIEFkbWluIEJsZGcKQ29y
dmFsbGlzLCBPUiA5NzMzMS01NTAzCgpFbWFpbDogbWFpbHRvOndlYm1hc3RlckBlYXJ0aHJlZi5v
cmcKCj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT0KCgo=

**Comment by rminnett** [comment]
That's base64 that apparently Thunderbird isn't decoding properly:

![image](https://user-images.githubusercontent.com/1182698/39066881-853800ec-448b-11e8-922f-3d2193211bcd.png)

Perhaps there's something we can do with the email headers so Thunderbird handles it properly.

**Comment by njarboe** [comment]
I imagine he receives Base64 encoded emails all the time (they are pretty common right?) and that they are working fine. I'd guess there is something a little different in our email from most Base64 emails that causes this to fail on his system. Not worth figuring out I think unless we find other people having the same problem I guess. I sent Michael about this issue and can reopen it if needed.

Hello Michael,

It looks like the email we send is encoded in Base64, which is commonly used, and your email system did not interpret it as Base64. Do you get other emails from people that show up with this scrambled text for time to time? If not there must be something in our email that is a bit off and we will look into it as time permits. If you do there is probably a bug in Thunderbird in decoding Base64 sometimes.

If you get similar emails from us in the future, you can let us know if you like and can also decode them at:
https://www.base64decode.org/

Cheers,
Nick

**Comment by rminnett** [comment]
That sounds reasonable for now.
