### ISSUE TITLE
Variations in the case of earthref.org/magic prevent correct redirecting

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#341]
For example: https://earthref.org/magIC/  

does not resolve to https://www2.earthref.org/MagIC

https://www2.earthref.org/magIC *does* resolve correctly, though.

**Comment by rminnett** [comment]
Thanks, any case should redirect properly now:

https://earthref.org/magic/
https://earthref.org/magIC/
https://earthref.org/Magic/
https://earthref.org/MagIC/
https://earthref.org/MAGIC/
