### ISSUE TITLE
Passed validation but no way to activate

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#355]
Passed validation but the validate button still visible and no activate button visible.
<img width="863" alt="screen shot 2018-06-11 at 8 06 13 pm" src="https://user-images.githubusercontent.com/1278789/41268030-19f16caa-6db3-11e8-8299-49f56cdf39fc.png">
<img width="950" alt="screen shot 2018-06-11 at 8 06 31 pm" src="https://user-images.githubusercontent.com/1278789/41268037-24eb202e-6db3-11e8-94fc-4c4dad79da32.png">

**Comment by rminnett** [comment]
Hm, ok, after validation passes, it's supposed to replace the "Validate" button with an "Activate" button. I'll update the beta site with a fix.

**Comment by njarboe** [comment]
Activate button is not visible but does not seem to do anything when clicked. No browser or other indication that something is going on and after 5 min, still nothing.

<img width="969" alt="screen shot 2018-06-12 at 7 42 20 am" src="https://user-images.githubusercontent.com/1278789/41297570-4469c02a-6e14-11e8-97e8-49dedc088da2.png">

**Comment by njarboe** [comment]
I get to the next screen, but that activate button does not work.
<img width="960" alt="screen shot 2018-06-12 at 8 28 18 pm" src="https://user-images.githubusercontent.com/1278789/41328892-4d8d2bea-6e7f-11e8-98de-b78425602275.png">

**Comment by njarboe** [comment]
Now its gone through. Need some kind of spinner or something to let the user know they need to wait.
