### ISSUE TITLE
locations.citations Validations description should be changed but I can't find it

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#356]
The locations.citations Validations description is a bit out of date. I wanted to update the text but could not find where that is. 
 
grep -r "this column could contain a value found in the" *

over the source found nothing and I couldn't find that text in the data model google doc. Did not see it in the locations.citations row and a search on "will be added" failed.

If you can point me to where this is, that would be great.

**Comment by rminnett** [comment]
Did you mean this to in the PmagPy issues?

**Comment by njarboe** [comment]
Nope. In the current 3.0 data model.
<img width="1015" alt="screen shot 2018-06-12 at 9 43 44 pm" src="https://user-images.githubusercontent.com/1278789/41330695-ec856528-6e89-11e8-9549-8d8df2696884.png">

**Comment by njarboe** [comment]
Thanks Rupert. Now fixed
