### ISSUE TITLE
Verson number not showing in most recent, Hnat et al. (2006), contibution

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#36]
The Hnat et al. (2006) contribution for some reason does not have the version number displayed. Same problem in the search interface.

![screen shot 2017-02-07 at 1 08 30 pm](https://cloud.githubusercontent.com/assets/1278789/22711587/974618b2-ed36-11e6-82f5-9649936c320c.png)

**Comment by rminnett** [comment]
This is related to #5. Once all of the contributions are in 3.0, it'll be easier to establish the version history and correctly set the version number. For now, I'm doing it by hand, which is why it's blank temporarily.

**Comment by rminnett** [comment]
I manually fixed this contribution.
