### ISSUE TITLE
links within the data model page are failing

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#364]
If I am browsing the data model,  then attempt to click on a 2.5 column link (i.e., contribution.id in this example):

![screen shot 2018-08-02 at 1 19 53 pm](https://user-images.githubusercontent.com/1836578/43608750-ca025764-9656-11e8-9bb4-5a49084604f0.png)

I get a 404 error.

If I click on a 3.0 column, as in a validation (in this case, sites.site):

![screen shot 2018-08-02 at 1 21 11 pm](https://user-images.githubusercontent.com/1836578/43608798-f8bbfe2a-9656-11e8-90ba-e2d5de6724e5.png)

it generates a "correct" url, (https://www2.earthref.org/MagIC/data-models/3.0?q=sites.site) but it displays the full unsorted data model page.

I encountered these problems on Safari, and I haven't tested them on other browsers.

**Comment by rminnett** [comment]
Thanks, Lori - I can reproduce the error and I'll look into a fix.
