### ISSUE TITLE
Activation date on Julie Bowles latest contribution seems incorrect

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#367]
I believe the activation date on Julie's last contribution should have been Aug 14th but the contribution is displaying the Aug 7th. Does not matter in this case, but would good to fix for future people. Maybe related to how you added the ref for this one?

![screen shot 2018-09-04 at 12 29 15 pm](https://user-images.githubusercontent.com/1278789/45053429-d43c9080-b03e-11e8-9e64-206e92273d52.png)
![screen shot 2018-09-04 at 12 29 28 pm](https://user-images.githubusercontent.com/1278789/45053441-d9014480-b03e-11e8-8479-0c82ae505581.png)

**Comment by rminnett** [comment]
Yes, it looks like it kept the upload date and didn't update it to the activation date. This is a valid bug.
