### ISSUE TITLE
Write API for Magic

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#368]
Write API for Magic

**Comment by rminnett** [comment]
This is ongoing, but we don't really need an issue for it.

**Comment by njarboe** [comment]
OK. Will add specific issues when working with the API.

**Comment by rminnett** [comment]
Sounds good - if it's an issue to do with using the API on the MagIC
website it can go on this repo, but issues or feature requests for the API
directly should go to https://github.com/earthref/FIESTA-API/issues and for
the examples notebooks to
https://github.com/earthref/FIESTA-API-Notebooks/issues.
