### ISSUE TITLE
Adding a description to a contribution erases all of the other columns in the contribution table

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#370]
If I upload this file, turn off the contribution table, and then add the DOI I get this contribution table:
tab delimited	contribution
version	timestamp	contributor	data_model_version	reference
5	2018-10-04T18:46:34.964Z	@njarboe	3.0	10.1002/2017GC007049
[magic_contribution_16511.txt](https://github.com/earthref/MagIC/files/2447710/magic_contribution_16511.txt)

(missing contribution id, but will post an issue for that separately)

Then when I add a description I get:
tab delimited	contribution
description
Adding a description messes up the contribution table

[magic_contribution_16511 (1).txt](https://github.com/earthref/MagIC/files/2447713/magic_contribution_16511.1.txt)

**Comment by rminnett** [comment]
Yes, I see - I'll look into a fix for that.
