### ISSUE TITLE
Validation does not catch missing required fields in the contribution table

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#371]
This file with missing required contribution columns passes validation.

[magic_contribution_16511 (2).txt](https://github.com/earthref/MagIC/files/2447720/magic_contribution_16511.2.txt)

The contribution table is:
tab delimited	contribution
description
Adding a description messes up the contribution table

![screen shot 2018-10-04 at 11 57 24 am](https://user-images.githubusercontent.com/1278789/46496369-bb093a00-c7cc-11e8-8d79-0dadb174654a.png)

**Comment by rminnett** [comment]
Technically, there's aren't any required fields in the contribution table. Which fields are you expecting it catch?

**Comment by rminnett** [comment]
The contribution metadata will be available in the download immediately after upload once #434 is addressed.
