### ISSUE TITLE
The contribution ID is not added to the contribution table

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#372]
Lori noticed that the contribution id is not included in the contribution table in:
[magic_contribution_16462.txt](https://github.com/earthref/MagIC/files/2447732/magic_contribution_16462.txt)
tab delimited	contribution
version	timestamp	contributor	data_model_version	reference	description
3	2018-05-07T18:21:16.698Z	@njarboe	3.0	10.1002/2017GC007049	Removes some errant rows from the site table

It is also missing in the most recent upload:
[magic_contribution_16505.txt](https://github.com/earthref/MagIC/files/2447734/magic_contribution_16505.txt)
tab delimited	contribution
version	timestamp	contributor	data_model_version	reference
1	2018-09-19T13:50:15.525Z	@AlbertoMC	3.0	HTTPS://DOI.ORG/10.1029/2018GC007781

**Comment by rminnett** [comment]
Yes, I see - I'll look into a fix for that.

**Comment by njarboe** [comment]
Looks good.
