### ISSUE TITLE
Contribution 16508 is has many blank headers in the measurements table

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#380]
When I download contribution 16503 and try to run download_magic, it fails because there are several blank leading column headers in the measurements table.  

<img width="1004" alt="screen shot 2018-11-06 at 1 56 59 pm" src="https://user-images.githubusercontent.com/1836578/48096375-db615580-e1cb-11e8-8081-ae02785ec810.png">

**Comment by rminnett** [comment]
Yes, I noticed that too (16508, not 16503, right?). I'm looking at how those got in there (they're in the original upload file, but should have been removed before saving the table).

**Comment by moonshoes87** [comment]
Yes, 16508.  Sounds good!

**Comment by njarboe** [comment]
I emailed Brendan about this problem and the site name inconsistancy. Hopefully he will get back to me soon. His other big data upload files seem to be in order with complete measurement headers and good site names.

**Comment by rminnett** [comment]
The measurement data are fixed now.
