### ISSUE TITLE
search confusing

### ISSUE THREAD

**Issue by ltauxe** [earthref/MagIC#382]
When i search for publication year 2004-2004 and L. Tauxe as an author, I get everything with L. Tauxe as an author, not just published in 2004.  
![screen shot 2018-11-19 at 10 37 13 am](https://user-images.githubusercontent.com/174861/48727534-5a508800-ebe7-11e8-884a-c755fce891c2.png)

**Comment by ltauxe** [comment]
now i get only three like you have.   but…   you see that v. 4 of the Snake River contribution is a later contribution than the v. 7 one.  
lisa

**Comment by rminnett** [comment]
Yes, Lori reported that in #383 and I'm working on a solution to resolve the duplicate DOI version histories. I'll close this issue for now, but feel free to re-open it if you get more strange search results.
