### ISSUE TITLE
version numbers incorrect for updated contribution

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#383]
We just fixed Tauxe 2004 and re-uploaded it.  We downloaded and fixed version 6, then uploaded it, and for some reason it  became version 3.  This seems like a bug.

Digging deeper, it looks like there are two separate id numbers for this one contribution:

https://earthref.org/MagIC/16530
https://earthref.org/MagIC/16520

DOIs are identical, so I don't know why this is happening.  
10.1029/2003GC000661

**Comment by rminnett** [comment]
Yes, this is directly related to the duplicate DOIs. When you add a DOI to the private contribution, it associates it with a previous contribution with that DOI if one exists. It looks like contribution ID 7532 in 2007 wasn't associated with the contribution ID 6547 correctly and resulted in two parallel version histories:

![image](https://user-images.githubusercontent.com/1182698/48729498-99350c80-ebec-11e8-89c2-0b1f75a8fb60.png)

Contribution ID 15843 was just an automatic upgrade of 6547, so I suggest that I make 6547 version 1, 7532 version 2, ... 16520 version 7 and 16530 version 8, and delete 15843. Does that sound right?

**Comment by moonshoes87** [comment]
Yes, that should be correct.

**Comment by rminnett** [comment]
Here's the combined contribution history now:

![image](https://user-images.githubusercontent.com/1182698/48759927-886eb000-ec59-11e8-9664-fa68c996bb29.png)
