### ISSUE TITLE
Don't require capitalization of controlled vocab.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#385]
I think it makes sense to ignore case in the vocab lists. I like to use lower case when that is the correct way of presenting the word. "America": capitalization correct. "Blanket Bog Peat":not really.

But we should be consistent in the database. Caps for all I suppose. 
So I would guess the best thing to do would be to warn the person that "basalt" will be changed to "Basalt" instead of saying "basalt" is not in the Lithologies list.

![screen shot 2018-12-05 at 12 11 50 pm](https://user-images.githubusercontent.com/1278789/49541811-b45c7900-f888-11e8-94f0-7e9030d9a27f.png)

**Comment by njarboe** [comment]
Looks like we just change them to the correct capitalization without warning at the moment. I guess that is fine. Just need not to throw an error then.

**Comment by rminnett** [comment]
Where are you seeing the capitalization getting corrected?

**Comment by njarboe** [comment]
I thought that I had not used capital letters in my original Bogue 2017 upload, but going back to my excel file, it looks like I had the capitals in the source. Sorry about that.

I think a warning that the terms will be capitalized is the best route, especially considering we are planning to also add calculated data to people's datasets with a similar warning in the future. Then change the data right then. If a persons downloads the file from the private workspace they get the corrected data. 

What do you think?

**Comment by rminnett** [comment]
Yep, that sounds good. I'm relaxing the validation to case-insensitive matches for controlled vocabularies (method codes still have to be capitalized, though).
