### ISSUE TITLE
Should we have only one name for a country

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#386]
Seems like we should have only one name for each country. At first glance we have:
U.S.A.
United States
United States of America

and
U.K.
United Kingdom

Change to one in controlled vocab and one in the Countries list.

**Comment by rminnett** [comment]
Perhaps the best solution is to have a primary value and alternate spellings so the cv() validation doesn't fail, but the data get replaced with the primary value on activation?

**Comment by njarboe** [comment]
So, remove the duplicate names in the cv but have a check in the validation logic that will look for alternatives and then warn the user the name with be changed to the one in the cv. Seems good.

**Comment by njarboe** [comment]
No other countries have abbreviations. I'm going to remove U.K. and U.S.A. Otherwise we are making those special exceptions that aren't really needed. If we get the more sophisticated validation running then we can put in acceptable other values for countries then.

**Comment by njarboe** [comment]
Updated
