### ISSUE TITLE
Have to validate again after adding DOI

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#387]
If i validate before adding the DOI and pass, it requires one to validate again after adding the DOI. I don't think this is needed.
After first validation
![screen shot 2018-12-05 at 12 38 31 pm](https://user-images.githubusercontent.com/1278789/49542686-1e761d80-f88b-11e8-815e-f08863978e0c.png)
After DOI addition validation has to be done again.
![screen shot 2018-12-05 at 12 38 52 pm](https://user-images.githubusercontent.com/1278789/49542727-36e63800-f88b-11e8-9fd4-914cdc96bf74.png)

**Comment by rminnett** [comment]
Yes, I agree - any change to the data is marking the validation as stale, but just updating the reference shouldn't need another validation run.
