### ISSUE TITLE
Upload does not replace previous version

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#390]
Richard Bono is having a problem with updating his private contribution. It is missing  the location table. Here I tried adding a site to the data file and it looks like it will work but then does not after the upload is complete.
File before:
[magic_contribution_16546.txt](https://github.com/earthref/MagIC/files/2654186/magic_contribution_16546.txt)

File with extra site that does not replace the original:
[sept_iles_03.Dec.2018_3MOD.txt](https://github.com/earthref/MagIC/files/2654187/sept_iles_03.Dec.2018_3MOD.txt)
![screen shot 2018-12-06 at 9 35 37 am](https://user-images.githubusercontent.com/1278789/49601508-d7476580-f93a-11e8-8dfc-254d1dc345aa.png)

After: Note still one site not two:
![screen shot 2018-12-06 at 9 39 14 am](https://user-images.githubusercontent.com/1278789/49601525-e62e1800-f93a-11e8-8477-697a0e5929ba.png)

**Comment by rminnett** [comment]
I'll have to look into why the preview of the summary is reporting 2 sites, but it looks like both files have only one site in them called "SI1". Is that right?

**Comment by rminnett** [comment]
@njarboe, can we close this issue if it works as expected (replaces sites table) - or is there still an issue to investigate here?

**Comment by njarboe** [comment]
@rminnett,
I uploaded the wrong file to github, not the website, so the issue still stands. I just retried it and got the same problem. You will have to turn of one column for some reason now to upload the files. This is a copy of a file that Richard Bono is trying to get updated in his private workspace.

[magic_contribution_16546.txt](https://github.com/earthref/MagIC/files/2660817/magic_contribution_16546.txt)
[magic_contribution_16546MOD.txt](https://github.com/earthref/MagIC/files/2660818/magic_contribution_16546MOD.txt)
Workspace with first file uploaded:
<img width="987" alt="screen shot 2018-12-09 at 9 37 33 am" src="https://user-images.githubusercontent.com/1278789/49700656-8633ad80-fb96-11e8-9874-957df20b1a7e.png">

Upload summary screen:
<img width="939" alt="screen shot 2018-12-09 at 9 38 11 am" src="https://user-images.githubusercontent.com/1278789/49700660-921f6f80-fb96-11e8-9016-3f72414361a2.png">

After trying to replace still one site:
<img width="969" alt="screen shot 2018-12-09 at 9 38 29 am" src="https://user-images.githubusercontent.com/1278789/49700664-a8c5c680-fb96-11e8-9098-b83c978240cc.png">
