### ISSUE TITLE
Add dir_n_specimens and dir_n_total_specimens to data model and propagate the changes to the website

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#394]
Add dir_n_specimens and dir_n_total_specimens to data model and propagate the changes to the website.

Need this for the demo so I can download file, edit with pmagpy, and reupload.

**Comment by njarboe** [comment]
Added to master online data model.

**Comment by rminnett** [comment]
I didn't see your commit to master - perhaps it didn't push? I've added them to the data model online and Elasticsearch and deployed to Galaxy. Let me know if there's still an issue with this.
