### ISSUE TITLE
Uploading to existing Contribution fails -  Error: [strict_dynamic_mapping_exception] 

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#396]
Uploading to existing Contribution fails - Failed to upload the file to your existing private contribution called Prevot 1985. Error: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [external_results] within [summary.sites] is not allowed [esUpdatePrivateContribution]
First file
[magic_contribution_15221.txt](https://github.com/earthref/MagIC/files/2661988/magic_contribution_15221.txt)
Second file:
[magic_contribution_15221MOD.txt](https://github.com/earthref/MagIC/files/2661990/magic_contribution_15221MOD.txt)
<img width="921" alt="screen shot 2018-12-09 at 11 41 33 pm" src="https://user-images.githubusercontent.com/1278789/49717502-1bbd5480-fc0c-11e8-9c62-298799b02c55.png">

**Comment by rminnett** [comment]
external_results wasn't mapped completely in Elasticsearch, but it is now.
