### ISSUE TITLE
Upload file fails - Error: [strict_dynamic_mapping_exception]

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#397]
Same as #396 but happens also when uploading to new contribution.
Would be good to figure this out before poster on Tues morning so that I can get a few more uploads on the page with more recent dates.

<img width="958" alt="screen shot 2018-12-09 at 11 44 20 pm" src="https://user-images.githubusercontent.com/1278789/49717658-a30ac800-fc0c-11e8-88c8-adae300754f2.png">

**Comment by rminnett** [comment]
external_results wasn't mapped completely in Elasticsearch, but it is now.
