### ISSUE TITLE
Contribution table is not being created/download correctly

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#401]
I'm try to get some data sets converted for Max and GEOMAGIA but the contribution table is not build right. For the most recent activation that I just did (Greve2017) only the description field is in the contribution table. I need the reference doi for my GEOMAGIA script to grab the reference. If you are not on vacation yet, it would be great to get this fixed before you leave. Max is trying to get GEOMAGIA out at the beginning of the new year and I would like to help him with some contributions in MagIC.
Here is the new downloaded file with the broken contribution table.
[magic_contribution_16575.txt](https://github.com/earthref/MagIC/files/2705658/magic_contribution_16575.txt)

**Comment by rminnett** [comment]
I fixed the issue with editing the description deleting the other contribution row data and fixed the 16575 contribution. I'll go through the previous contributions and fix the ones that are missing IDs and other contribution data.

**Comment by njarboe** [comment]
Ok. That will be good. Thanks.
