### ISSUE TITLE
wrong DOI for new contribution

### ISSUE THREAD

**Issue by ltauxe** [earthref/MagIC#402]
I just uploaded a new contribution and the publication DOI is incorrect. see:  
![screen shot 2019-01-04 at 4 10 11 pm](https://user-images.githubusercontent.com/174861/50717323-6a0f1900-103b-11e9-9099-921778c5fd19.png)

this contribution uses samples from  previous publications and the incorrect DOI is for one of those publications.

**Comment by rminnett** [comment]
It looks like it's fixed now - did you fix it, @ltauxe?

![image](https://user-images.githubusercontent.com/1182698/50721523-7787da00-10f3-11e9-8cdf-2727c93c43ce.png)

**Comment by ltauxe** [comment]
no - maybe it just took a while.  thanks for checking.
lisa

**Comment by njarboe** [comment]
I'll keep an eye out for this in the future
