### ISSUE TITLE
contribution 15349 is missing measurements.sequence

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#403]
This contribution is missing the required column measurements.sequence when downloaded.

**Comment by njarboe** [comment]
Link to contribution page: [https://earthref.org/MagIC/15349]
measurements.sequence is a new column in 3.0 and will not be in most older contributions, I believe. 
@rminnett, Did you try and fill out the sequence in the conversion to 3.0? Is there any easy way to just fill it in with the row order for those contributions that don't have it?

**Comment by rminnett** [comment]
Sure, if measurements.sequence is missing and measurements.measurement is an integer, I can copy it into the required sequence column.

**Comment by rminnett** [comment]
@moonshoes87, @njarboe while I was looking at it, this contribution has "Invalid date" in the measurements.timestamp field for some rows and columns - is this a PmagPy bug that needs an issue?

**Comment by moonshoes87** [comment]
@rminnett, could you give me an example of one of the invalid dates?  I don't have any validations for dates in PmagPy.

**Comment by rminnett** [comment]
Sure, @moonshoes87, https://earthref.org/MagIC/15349 does in the measurements table (search for "Invalid date")
[magic_contribution_15349.txt](https://github.com/earthref/MagIC/files/2872368/magic_contribution_15349.txt)

**Comment by rminnett** [comment]
Closing and adding to list in #374 for measurements.sequence to be filled in programmatically.

**Comment by moonshoes87** [comment]
@rminnett, I grepped for "Invalid date" in PmagPy and couldn't find a place where it would be added to  files.  Do we have any idea which PmagPy programs might have been used to generate this column?  A particular import script, perhaps?  Otherwise, it's a bit of a needle in the haystack for me...

**Comment by rminnett** [comment]
Ok, in that case it could either be from a Python date to string conversion (a quick search online didn't unearth any documentation about strftime() or Pandas casting an invalid date to a string of "Invalid date", though), or the data were entered that way from the start (in which case the online validation tool will now complain). I added a note to #374 so I can remove those strings programmatically since measurements.timestamp is not required.
