### ISSUE TITLE
After pressing "Activate" it takes some time for the new one to appear on the recent list on the homepage

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#409]
After pressing "Activate" it takes some time for the new one to appear on the recent list on the homepage. Over 5 seconds so that when I go back to the homepage I don't see it right away. This will confuse people and make them feel frustrated and mad at the software. After a lot of work and frustration, someone will finally activate and not see it made public. I think this was not a problem in the recent past, so I'm not sure what might have changed. Will add comments here if other ones seem to come up fast.

**Comment by rminnett** [comment]
Will be addressed with #427
