### ISSUE TITLE
Older .xls file fails to upload, but no error given

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#41]
This xls file from Jon Hagstrum at the USGS, when I drag it to the upload spot, goes immediately to success. No choice of columns presented like the example Excel file does. If I upload it to a private space, this is all that is created:

tab delimited	contribution
id	version	timestamp	contributor	magic_version
11878	PRIVATE	2017-02-11T00:32:44.743Z	@njarboe	3.0

[BOR_PM_GoodAges.xls.zip](https://github.com/earthref/MagIC/files/768116/BOR_PM_GoodAges.xls.zip)
(Zipped due to xls files not supported for uploading to github.)

Switching around the file type also is a bit off. If I switch it from Excel to MagIC Text File and back, the page says it is still parsing as a MagIC Text File.

<img width="978" alt="screen shot 2017-02-10 at 4 44 21 pm" src="https://cloud.githubusercontent.com/assets/1278789/22849253/385a4360-efb0-11e6-9d47-c3bf5d23738b.png">

**Comment by rminnett** [comment]
This should be resolved in the latest commit. Let me know if you're still having trouble.
