### ISSUE TITLE
Number validation failure

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#416]
Number validation failure with this upload(you have to turn off 4 blank columns that is making it through the system somehow. I will make new issue on that). Seems these values should be valid numbers.
[magic_contribution_16595MOD.txt](https://github.com/earthref/MagIC/files/2843505/magic_contribution_16595MOD.txt)
![screen shot 2019-02-07 at 7 23 12 pm](https://user-images.githubusercontent.com/1278789/52457336-1b5b1000-2b0e-11e9-9827-90b0ce1a1156.png)

**Comment by rminnett** [comment]
![image](https://user-images.githubusercontent.com/1182698/52459298-3717e380-2b19-11e9-9088-f9b0b2da7547.png)
