### ISSUE TITLE
Blank columns in data file when turned off during upload

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#417]
Blank columns get into data file when turned off during upload. This is the downloaded file with blank columns in the measurement table. This does not seem so bad but it breaks PmagPy and the upload->download->look at in PmagPy->export from PmagPy --> upload loop, so I set it to priority 1. 
[magic_contribution_16595.txt](https://github.com/earthref/MagIC/files/2843516/magic_contribution_16595.txt)
Here are screen shots uploading this contribution.
![screen shot 2019-02-07 at 11 43 03 am](https://user-images.githubusercontent.com/1278789/52457488-e0a5a780-2b0e-11e9-86d9-26546b24c3c0.png)
![screen shot 2019-02-07 at 11 46 30 am](https://user-images.githubusercontent.com/1278789/52457491-e4d1c500-2b0e-11e9-9a69-214c76662254.png)
![screen shot 2019-02-07 at 11 46 37 am](https://user-images.githubusercontent.com/1278789/52457493-e7ccb580-2b0e-11e9-8b74-781f7d2f6136.png)
![screen shot 2019-02-07 at 11 51 02 am](https://user-images.githubusercontent.com/1278789/52457497-ebf8d300-2b0e-11e9-959d-6594ced95cee.png)

**Comment by rminnett** [comment]
I think this only happens for measurements because of the way they're stored differently, but I'll look into a fix.
