### ISSUE TITLE
xlsx import on simple file won't allow "Number of Header Rows" to be set

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#42]
Using Chrome.

With this file: 
[App1DAT.xlsx](https://github.com/earthref/MagIC/files/771990/App1DAT.xlsx)

Parsing as an Excel file and setting the table name to "Sites" (or anything else), I cannot set the "Number of Header Rows". No response in that box.

**Comment by rminnett** [comment]
This should be resolved in the latest commit. Let me know if you're still having trouble.
