### ISSUE TITLE
Too much whitespace in new plotting tabs view

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#437]
Due to lots of unneeded whitespace the main plot in the plot display is now very small and hard to read. If you can remove the padding from every element, I think that would work much better.

<img width="1190" alt="screen shot 2019-02-18 at 9 11 30 pm" src="https://user-images.githubusercontent.com/1278789/52991585-204b7980-33c2-11e9-93bd-6aaf40f20df2.png">

**Comment by rminnett** [comment]
Yep, I'm working on some more improvements to this including using the full page for the thumbnails and overlaying the plot over the entire list when you click on it.
