### ISSUE TITLE
Validation should allow integer floats in integer columns

### ISSUE THREAD

**Issue by rminnett** [earthref/MagIC#440]

**Comment by njarboe** [comment]
@rminnett  Did you make this change or leave it like I first suggested? The number 8.0 would not validate as an int and should throw an error on validation. We could change that to a warning when we have that system in place.

**Comment by njarboe** [comment]
Added this to issue #441 which will be a list of such features for a future validation extension.

**Comment by rminnett** [comment]
I had changed it locally, but it's only a few lines. I'll change it back.
