### ISSUE TITLE
Add navigation to plots and show 100 per page

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#443]
Put a row of buttons on the bottom of a plots thumbnail page with 100 increments so one does not have to scroll through the whole set to look at a specific plot.

Increase the number of thumbnail plots displayed to 100.

**Comment by njarboe** [comment]
![Screen Shot 2019-03-17 at 4 32 37 PM](https://user-images.githubusercontent.com/1278789/54499810-25bdb600-48d3-11e9-85b0-a332a58ae51b.png)

**Comment by rminnett** [comment]
I'll implement this as scrolling with placeholders for the thumbnails that load when they come into view.

**Comment by rminnett** [comment]
Here's a start:

![image](https://user-images.githubusercontent.com/1182698/55121846-ae99d600-50b9-11e9-92c1-a7f3b7dcfbcd.png)
