### ISSUE TITLE
Can't turn off first line of table when uploading

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#447]
Can't turn off first line of table when uploading.
This file has three lines in the locations table that need to get turned off, but there is no way to do that for the first line. Can't import this file as is.
![Screen Shot 2019-03-22 at 3 34 48 PM](https://user-images.githubusercontent.com/1278789/54856573-66914280-4cb8-11e9-95d4-9f440dfefdbd.png)

**Comment by njarboe** [comment]
For to include the excel file, so here is one with just the locations table that also has this error.
[locationWang15.xlsx](https://github.com/earthref/MagIC/files/2998514/locationWang15.xlsx)

**Comment by rminnett** [comment]
With locationWang15.xlsx, I think the table has to be rotated first since the rows are the data fields.

In both cases, though, doesn't increasing the number of header rows let you skip those initial lines?

![image](https://user-images.githubusercontent.com/1182698/54869531-2fbe3980-4d57-11e9-8be7-31fa45d2b9d6.png)

**Comment by njarboe** [comment]
Yes. That works. Maybe an addition to make things a bit simpler for people using my Excel template. I added some description text at the top and now one sees many errors when uploading until the number of header rows is set correctly. 

It would be great to have it search down the first row of the table and if it finds the table type as a value, set the number of header rows appropriately. So in this file on the locations table since location is in column 1 row 2 the number of header rows would be set to 2.

Merielle and I were going over this and that would make using the template more friendly. She is giving a talk on Sunday in Vienna to EPOS people that we are working on this week.

[Template3.0ForMagICUpload.xlsx](https://github.com/earthref/MagIC/files/3040809/Template3.0ForMagICUpload.xlsx)

**Comment by rminnett** [comment]
That commit was supposed to close #456

**Comment by njarboe** [comment]
Changed priority as the number of header rows works to cut off extra header rows.

**Comment by njarboe** [comment]
Now website sets the number of header rows to 2 for the excel template. Great.
