### ISSUE TITLE
Giving the direction polarity should not require other fields in the direction group to be filled out

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#448]
Giving the direction polarity should not require other fields in the direction group to be filled out. In fact I think that so many studies have variations on what they publish that the direction fields should not have that restriction.

With this in place one can't activate some papers when all data in the paper is included. For example, polarity is given but not direction.

**Comment by rminnett** [comment]
Is this requirement satisfied by removing the requiredIfGroup("Direction") validations?

**Comment by njarboe** [comment]
Will revisit if the problem comes up again.
