### ISSUE TITLE
Full view of plots is distorted on Safari

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#455]
<img width="1264" alt="Screen Shot 2019-04-30 at 2 01 05 PM" src="https://user-images.githubusercontent.com/1836578/56993200-b2a19380-6b50-11e9-8942-a500ec76749c.png">

<img width="1262" alt="Screen Shot 2019-04-30 at 2 04 13 PM" src="https://user-images.githubusercontent.com/1836578/56993279-e086d800-6b50-11e9-91b5-b4898ac60b50.png">

**Comment by rminnett** [comment]
It's better now in that the aspect ratio is preserved, but Safari doesn't update the grey border around the fitted image like Chrome and Firefox do:

![image](https://user-images.githubusercontent.com/1182698/58117493-f1f55a00-7bbb-11e9-8dc1-0e4306fac8bc.png)
