### ISSUE TITLE
can't upload a ~500 line images file to private workspace

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#456]
On Safari, trying to upload an images file just hangs indefinitely:

<img width="1195" alt="Screen Shot 2019-05-13 at 12 21 23 PM" src="https://user-images.githubusercontent.com/1836578/57648241-cfd75880-7579-11e9-8ad1-b8b3b876aa82.png">

**Comment by njarboe** [comment]
Would you attach the file you were trying to upload so I can give it a try. Thanks.

**Comment by moonshoes87** [comment]
This is the images file from the McMurdo dataset in the PmagPy repo, and it exhibits this issue for me on Safari:

[images.txt](https://github.com/earthref/MagIC/files/3192928/images.txt)

**Comment by rminnett** [comment]
If it's just an images table on its own, that might cause problems for the summary - I'll work out a fix for this.

**Comment by njarboe** [comment]
I added the image file to the McMurdo MagIC file and it does upload. Here is the that file.
[magic_contribution_16436MOD.txt](https://github.com/earthref/MagIC/files/3204065/magic_contribution_16436MOD.txt)

It takes a bit of time to get into the private contribution with so many measurements.
