### ISSUE TITLE
Bryson file gets a "Request Entity Too Large" error on uploading

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#459]
I got one scan of the Bryson data in a MagIC file, but it is over a million measurements and I get an error that it is too big:
![Screen Shot 2019-07-22 at 3 48 14 PM](https://user-images.githubusercontent.com/1278789/61671222-7e46fa80-ac9b-11e9-9469-bbcafc79fee6.png)
How do you think we should proceed given that he would like to get 107 additional scans in also? My current code can create one huge measurement file or I can break it into parts.

I shared the data file, Portales-Valley-Meteorite_22.Jul.2019.txt, with you via Dropbox.

**Comment by rminnett** [comment]
Excellent, thanks, I'll take a look at the options!

**Comment by rminnett** [comment]
These large contributions will be handled more gracefully with the API instead of the web client upload.
