### ISSUE TITLE
Controlled vocabularies has locked icon

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#46]
This is currently accessible, so should not have the locked icon?

<img width="343" alt="screen shot 2017-02-24 at 4 33 58 pm" src="https://cloud.githubusercontent.com/assets/1836578/23326115/97072f18-faaf-11e6-9045-41aacd8ef16d.png">

**Comment by rminnett** [comment]
Ah, I can see that might be misleading. I just chose that lock icon because some of the lists are “locked” as in “controlled”, not “locked” as in “inaccessible”. If you see a better secondary icon to use for the corner in this list, it’s easy to change: http://semantic-ui.com/elements/icon.html

**Comment by moonshoes87** [comment]
Ah, I think that was confusing to me because you previously used the lock symbol to indicate unfinished parts of the beta site, right?  I don't necessarily see a better option among the semantic ui icons.
