### ISSUE TITLE
Uploading Herve2019 files fails on summary page

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#464]
Uploading Herve2019 file fails on summary page.

![Screen Shot 2019-10-18 at 3 00 18 PM](https://user-images.githubusercontent.com/1278789/67131115-44ad5f00-f1b8-11e9-80f3-745855450d4e.png)

[Herve2019MagIC-3.xlsx](https://github.com/earthref/MagIC/files/3745913/Herve2019MagIC-3.xlsx)

**Comment by rminnett** [comment]
I added the Elasticsearch mappings and it uploads now:

![image](https://user-images.githubusercontent.com/1182698/67133694-d4580b00-f1c2-11e9-8d31-01fdebf09bed.png)
