### ISSUE TITLE
Data Model 3 - best fit vector for plane fits

### ISSUE THREAD

**Issue by Caoimhinmg** [earthref/MagIC#47]
Hi @rminnett, not sure if this is the right place to drop this request, but it's what I found fastest.

Anyway I've had some requests to add viewing and exporting of best fit vectors to plane fits in Demag GUI mostly because the vector used in fisher means is this best fit vector not the pole of the plane fit to the data. This is because the pole which is orthogonal to the plane fit would be a complete outlier as it would be more or less perpendicular to the line fit data. However to save the plane itself you need to export the normal vector which is what Demag GUI does in the dir_dec and dir_inc spots of data model 3 if you've made a plane fit. So if I'm to export the best fit vector which might be useful for viewing a plane fit in context of the other fits I will need a new set of entries in the data model, possibly plane_best_fit_dec, plane_best_fit_inc or something like that. @njarboe can probably come up with a better variable name, but anyway not a big priority though I would like to get this done in the next month or so finally completing Demag GUI's support for plane fits.

**Comment by rminnett** [comment]
Sure, I think we can do that. It's just a matter of making sure we can't reuse existing columns first.

Which tables would need these two new best-fit plane columns?

**Comment by Caoimhinmg** [comment]
Specimens is basically the only table that needs this. This is because higher level statistics such as Samples, Sites, Locations all use this best fit vector to calculate Fisher means, but don't have one being you know Fisher means not plane fits.

**Comment by rminnett** [comment]
Ok, I think we'll just add them to the Directional Statistics group in the Specimens table. I'll let you know when the model is updated online.

**Comment by njarboe** [comment]
I have added dir_plane_dec and dir_plane_inc to the 3.0 data model in the specimens table. The Column Name is "Direction Best Fit Plane Declination" and the description is "Declination of the vector orthonganal to the best filt plane of the specimen demag in coordinates specified by tilt correction". Inclination is similar. Will this work?

**Comment by Caoimhinmg** [comment]
Ah @njarboe, The values you just added are what dir_dec and dir_inc are currently used for. This is because those values are necessary to define the best fit plane (bfp) which cannot be defined by a vector inside the bfp. So I suppose the idea is that the dir_plane_dec (maybe better as dir_bfv_dec) and dir_plane_inc (maybe better as dir_bfv_inc) be the direction of the best fit vector (bfv) which is inside the bfp and which is calculated to be used in Fisher means. Preservation of this data allows easier comparison to other interpretation types as it displays the data actually incorporated in high level means, however, I think we should keep dir_dec and dir_inc as the normal vector of the bfp as it is the defining value of the interpretation. So basically I need a field for the bfv direction not for the normal vector direction. Hopefully this isn't too hard to change.

**Comment by njarboe** [comment]
@Caoimhinmg, So is the issue that if one has only the vector orthogonal to the plane does not know with only that info which dmag points that define the plane were the first or last in the demag sequence? That is, one does not know in what direction the the demag vector is heading toward? How does one determine what your describe as the best fit vector in the plane and what does its direction mean? It sounds to me it might be best to add both bfp and bfv so one can stop using dec and inc to describe bfp when that is not what the dec and inc columns are defined as. Some juggling the pmag programs would be in order. Do you think I should add dir_bfp_dir/inc and dir_bfv_dir/inc? Seems best to me.

**Comment by Caoimhinmg** [comment]
@njarboe, basically yes. The bfv is determined iteratively inside the plane to be close to the direction of the other vectors you are taking a fisher mean with. So if you don't export the bfv you don't actually know the vector used in the high level means when you do a plane fit, you just know the orthogonal to the plane which is not really very helpful, and because you need to have every vector used in the fisher mean to calculate the bfv it's not really something you can just do fast without reloading the whole dataset either.

I agree that using both dir_bfp_dec/inc and dir_bfv_dec/inc would be best, but as of right now I am tied up working on converting PmagPy to Python3 and I will be starting my PhD work at Rice in about 2 weeks so I'm not sure I have the time to rewrite and catch all the parts of Demag GUI that will break in such a change. It also is worth noting that such a change would probably mess with other parts of the other GUIs. So for now just the dir_bfv would be easiest, and maybe once PmagPy is in Python3, I've moved cross country, and I get settled in we can talk about switching dir_dec/inc to dir_bfp_dec/inc and what ramifications that'll have on PmagPy end. Thanks.

**Comment by njarboe** [comment]
I think I will add dir_bfp_dec/inc and dir_bfv_dec/inc to future proof the
data model and you can keep using the dir_dec/inc column of dir_bfp_dec/inc
until you want to make the switch.

Hope you enjoy your time at Rice. I was an undergrad in geophysics there
back in the day. What department are you in and do you have a thesis
advisor yet?

**Comment by Caoimhinmg** [comment]
Thanks @njarboe. This is a great solution.

I am going to Rice as a geophysics PhD student in Richard Gordon's lab (co-sponsored by Adrian Lenardic) in the Earth Science Department. Should be a lot of fun I really like the campus and am looking forward to my new projects. Though I am sad to not be able to work with PmagPy as much.

**Comment by njarboe** [comment]
@Caoimhinmg, I added dir_bfv_dec/inc to the data model and changed dir_plane_dec/inc to dir_bfp_dec/inc. Hopefully we can drag you back to PmagPy from time to time.
