### ISSUE TITLE
Add ages to the DataCite record

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#480]
Add ages to the DataCite record.

**Comment by rminnett** [comment]
New DataCite records include the ages:

https://ezid.cdlib.org/manage/display_xml/doi:10.7288/V4/MAGIC/16814

I'm reprocessing existing DataDOI metadata to include ages.

**Comment by njarboe** [comment]
People looking at the DataCite record won't know that our default age unit is BP. I think you should add it, if that is not too much work. EPOS will know since we are in contact with them, but for others it would be useful.
<subject subjectScheme="earthref.magic.age_unit">BP</subject>

**Comment by rminnett** [comment]
Yep, that makes sense! Now I'm including the age_unit, schemeURI, and valueURI (if the value is part of a controlled vocabulary):

https://ezid.cdlib.org/manage/display_xml/doi:10.7288/V4/MAGIC/16814
