### ISSUE TITLE
Contribution Reference (reference) shows that it is required and suggest on the data model webpage

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#483]
Contribution Reference (reference) shows that it is required and suggest on the data model webpage. Not labeled as suggested in the google doc data model.

<img width="1099" alt="Screen Shot 2020-03-10 at 7 44 11 PM" src="https://user-images.githubusercontent.com/1278789/76377406-0bf95800-6308-11ea-9bd6-f2d53f194c91.png">
![Screen Shot 2020-03-10 at 7 45 50 PM](https://user-images.githubusercontent.com/1278789/76377583-7b6f4780-6308-11ea-9814-dd6b924bfdbd.png)

**Comment by rminnett** [comment]
The "Suggested" is referring to the vocabulary, not the suggested()
validation. I'm working on updates to the data model browser to hopefully
make this a bit more clear.

**Comment by njarboe** [comment]
Ok. But references are not a controlled vocab. Let me know when you have updated the model browser and I'll take a look.

**Comment by rminnett** [comment]
Ah, in this case it was referring to the type() validation - I'll make it more clear.

**Comment by rminnett** [comment]
The reason it was labeled as a suggested vocabulary, though, was because the original intent was to form a suggested vocabulary from the current references in ERR and MagIC. The type() validation can at least describe the fact that is must be either a DOI or URL that can be resolved.

**Comment by rminnett** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/1182698/76384996-c182d600-631d-11ea-84e7-cffa10f6425e.png)

**Comment by njarboe** [comment]
This is nice. I especially like the green Required (?) which helps people figure out complicated requirements like ages.
