### ISSUE TITLE
Have the links to vocabs open the corresponding vocab

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#484]
It looks like the link is set up to do this with a unique query string, but it doesn't work.
Would be nice to have for the Monday demo.

![Screen Shot 2020-03-11 at 12 20 24 PM](https://user-images.githubusercontent.com/1278789/76455428-f5e4a980-6392-11ea-860e-2c5823f75182.png)

**Comment by rminnett** [comment]
Yes, I see - I'll sort that out.
