### ISSUE TITLE
Search on data model shows groups with 0 search results

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#486]
It would be better if only the groups that had results were shown.
![Screen Shot 2020-03-13 at 1 19 33 PM](https://user-images.githubusercontent.com/1278789/76656782-92db4a00-652d-11ea-9b77-019c5bc47c62.png)

**Comment by rminnett** [comment]
https://earthref.org/MagIC/data-models/3.0?q=vadm seems to only show the matched columns:

![image](https://user-images.githubusercontent.com/1182698/76726765-63843300-670f-11ea-812f-81dd1a29bd62.png)

Can you provide a link that reproduces the issue, please?

**Comment by njarboe** [comment]
Will open new issue with the search parameters if I run into this again.
