### ISSUE TITLE
2nd upload of Reilly 2018 did created a new contribution not a new version

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#493]
2nd upload of Reilly 2018 did created a new contribution not a new version:
[magic_contribution_16793.txt](https://github.com/earthref/MagIC/files/4346305/magic_contribution_16793.txt)
2nd version:
[magic_contribution_16796.txt](https://github.com/earthref/MagIC/files/4346308/magic_contribution_16796.txt)

**Comment by rminnett** [comment]
Not sure what caused this, but fixed manually.
