### ISSUE TITLE
text entry with the new private workspace boxes is too slow

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#500]
Entering some text in the boxes on the new private workspace is now very slow. It takes about 10 seconds to the interface to respond between typing the text and the text showing up. Saving the description is also very slow at 15 seconds. This is going to make people think the site is broken.

Using Chrome.

**Comment by njarboe** [comment]
Rupert said this is due the the fact that the page refreshes with each key stroke. When one has many contributions in one's private workspace, this is very slow. The current idea for a fix is to have tabs in the private workspace so that activated ones and private ones are separate. People aren't likely to have many unactivated contributions, while the activated ones keep increasing over time.

**Comment by rminnett** [comment]
I added "In Preparation" and "Made Public" toggle buttons to the Private Workspace view to hopefully help with this for now:

![image](https://user-images.githubusercontent.com/1182698/92004907-a9ea4000-ecf7-11ea-84d3-3cec907af4f4.png)

**Comment by njarboe** [comment]
Now there is no delay with 3 contributions in my private workspace. Great.
