### ISSUE TITLE
Reilly et al. (2016) contribution goes to a page displaying the file instead of an option to download a zip file

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#501]
The recent Reilly et al contribution that you attached the measurements to does not allow downloading to a file. It displays the file in the browser and since it is so large takes a long time to load. Did not finish after 5 minutes. Other ones work fine.

**Comment by njarboe** [comment]
Same problem with the Jones 2020 contribution: magic_contribution_16786.txt

**Comment by rminnett** [comment]
It should download the zip file when you click on the Download button now: https://earthref.org/MagIC/16798

Should I also zip up 16786? The browser is deciding to display it as text in a tab rather than downloading, but since it's not as big, it should still finish and users can use the browser Save As command.

**Comment by njarboe** [comment]
The problem was that clicking the download button for those two contributions were displaying a text page instead of popping up a save or open dialogue box. We want consistent behavior and the popup works best. For very large files, we will want to have a rule for when we zip up the data. For now we can just do the ones that have multiple measurement files (like the SQUID ones from MIT). If we get any ones like Reilly et al. (2016) that are over 1GB, we should zip those up also.

Sorry for the not describing the problem more precisely and causing you more work. I'll try to be more exact in the future.

**Comment by rminnett** [comment]
No problem, it wasn't confusing. It's just that Jones 2020 falls somewhere
in the middle: too big to result in an automatic download in the browser
(it just shows the text file), but smaller than we would normally consider
for zipping up. I can just manually zip up anything that results in the
browser displaying it as a text file for now and rely on the API zipping up
any download in the future.

**Comment by njarboe** [comment]
Ok. Thanks for the info.
