### ISSUE TITLE
List of search improvements and changes

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#516]
Move the Author List to the top of the sidebar.
Add a search box to enter an author's last name in addition to an author list.
Make all of the pulldown lists in alphabetical order.
Clear to the right of the search box should also clear the filters. Should bring search back to all of the contributions.
Remove "Show More" button from the drop downs so that one can use a text search right away to find terms.

**Comment by rminnett** [comment]
- [ ] Move the Author List to the top of the sidebar.
- [ ] Add a search box to enter an author's last name in addition to an author list.
- [ ] Make all of the pulldown lists in alphabetical order.
- [ ] Clear to the right of the search box should also clear the filters. Should bring search back to all of the contributions.
- [ ] Remove "Show More" button from the dropdowns so that one can use a text search right away to find terms.
- [ ] Make numerical filters collapsed by default.

**Comment by njarboe** [comment]
1) As you stated in your email, move the Publication year. I would say to the top so that you can still see it when one selects the Author(s).

2) The individual text box search only works when you type in the search term in all lower case "tauxe" matches "Tauxe" and "TAUXE" but "Tauxe" and "TAuxe" do not. It should be case insensitive, but the minimal functionality must be "tauxe" or "Tauxe" or "TAUXE" finds "Tauxe" and "TAUXE".

![Screen Shot 2020-09-11 at 9 54 49 AM](https://user-images.githubusercontent.com/1278789/92952575-0f83ae00-f415-11ea-9165-896f85330683.png)

3)Hitting the "Clear" all filter cleared the Author filter name from the box, but still shows the previous author selection search list. 

![Screen Shot 2020-09-11 at 10 06 33 AM](https://user-images.githubusercontent.com/1278789/92953412-866d7680-f416-11ea-90b8-6342adc4d4de.png)

4) "Make numerical filters collapsed by default."
Having a few of the search parameters already open when first going to the search interface I think would be a good idea. It gives people a better clue that the arrows can be clicked on for opening the search parameters (although I'm not sure how obvious that will be to people) and gives quicker access to some of the most usual search parameters. Having a few open so that one can still see all the other search options is important, so I would suggest having only the Publication Year, Geospatial, and Age filters open. 

5) Add a collapsing arrow to search lists, but default open. That way one can close them when doing a complicated search and still see all of your search parameters on the screen at the same time.

**Comment by rminnett** [comment]
- [ ] Move Publication Year to the top.
- [ ] Use lowercase of find a filter input for matches.
- [ ] Clear find a filter matches with clear buttons.
- [ ] Keep Publication Year, Geospatial, and Age filters open by default.
