### ISSUE TITLE
Search for column names with just one letter does not work

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#54]
It would be nice if one typed in "R" or "R " that "Direction R" would pop up as an option. Also useful for N to show various N options.

**Comment by njarboe** [comment]
Inconsistently, the search does work with a "k". It finds Direction K.

**Comment by njarboe** [comment]
Tested. Still valid.

**Comment by rminnett** [comment]
Perhaps this was fixed already, but it appears to be resolved now:

![image](https://user-images.githubusercontent.com/1182698/92512016-04394400-f1c3-11ea-9a61-ebfe17b1297c.png)

Typing "R" does match "Direction R" in the specimens table, but it also matches many other columns with the letter "r" in it, whereas "K" produces a much shorter list of matches.
