### ISSUE TITLE
How to show the data from the private work area to reviewers when the article is under review?

### ISSUE THREAD

**Issue by njujxli** [earthref/MagIC#556]
I can only find the DOI number of published articles. What link can I use to show the data of private workspace to reviewers？Thanks!

**Comment by rminnett** [comment]
Hi! You should see a "Share" button in the top right of your contribution in the private workspace. Clicking on that gives you a link that contains a private key. You can share that URL with your colleagues and reviewers so they can see your contribution in the search interface even though it is private and even if they are not logged in (you can verify this by logging out and going to that URL).

Let us know if that doesn't work or if you need any more help!

**Comment by njujxli** [comment]
> Hi! You should see a "Share" button in the top right of your contribution in the private workspace. Clicking on that gives you a link that contains a private key. You can share that URL with your colleagues and reviewers so they can see your contribution in the search interface even though it is private and even if they are not logged in (you can verify this by logging out and going to that URL).
> 
> Let us know if that doesn't work or if you need any more help!

Thank you very much. I have found it. Thank you for your super fast reply！

**Comment by rminnett** [comment]
No problem, happy to help!
