### ISSUE TITLE
Longitude incorrect

### ISSUE THREAD

**Issue by Macking104** [earthref/MagIC#577]
The longitudes on Bogue 2018 are incorrect. Cant be 200
https://www2.earthref.org/MagIC/17056

S. W. Bogue (2018). Correlated Relative and Absolute Geomagnetic Paleointensities From a Pliocene N-R Polarity Reversal Record in Basaltic Lava Flows on Kauai, Hawaii. Geochemistry, Geophysics, Geosystems 19 (12):4773-4787. doi:[10.1029/2018GC007748](https://dx.doi.org/10.1029/2018GC007748).

**Comment by Macking104** [comment]
![IMG_8742](https://github.com/earthref/MagIC/assets/171116775/453903d7-00f6-418c-8d74-6dd7c1a03742)

**Comment by njarboe** [comment]
MagIC uses 0 to 360 East longitude for its longitude convention. So 200.35 E is the island of Kauai.
