### ISSUE TITLE
Private Workspace button fails to load private workspace

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#63]
Looks like the link needs a '#' at the end to work. The current link just hangs on the loading icon.
![screen shot 2017-04-13 at 10 55 46 am](https://cloud.githubusercontent.com/assets/1278789/25017260/e9e4b93c-2037-11e7-849e-7762d14992e7.png)

**Comment by rminnett** [comment]
This is slow because it's trying to load the complete contribution for each contribution in the workspace. It'll get better after everything is in 3.0, but I'll see if I can speed it up in the meantime.

**Comment by rminnett** [comment]
Fixing the memory leak issue has resolved this.
