### ISSUE TITLE
Date on recent contribution should show time and date, not for example: "Yesterday at 12:20"

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#7]
Show time and date of upload, not how far in the past it was uploaded.
![screen shot 2017-01-30 at 10 25 47 pm](https://cloud.githubusercontent.com/assets/1278789/22454501/15bebdea-e73b-11e6-8263-3a7867abca1d.png)

**Comment by rminnett** [comment]
I'm using the moment().format('ll') format now instead of moment().calendar(): https://momentjs.com/docs/#/displaying/

Let me know if you think something else is better.
