### ISSUE TITLE
The most recent Fleck et al. (2014) contribution (earthref.org/MagIC/11929) does not download

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#77]
The most recent Fleck et al. (2014) contribution (earthref.org/MagIC/11929) that Jon uploaded on Friday does not download. I believe we did down load it on Friday, although there was problems with the file format.

**Comment by rminnett** [comment]
This should work now. I moved your version to the history and you can download both now. Let me know if there are any other issues.

**Comment by njarboe** [comment]
Downloading works now.
