### ISSUE TITLE
Recent Contributions takes too long to load (more than a minute). 

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#8]
This is especially annoying when hitting the back button. Does it have to reload instead of just showing the previously loaded page as usually expected for a back button. 

Now more than 5 min. Aborting. Looks like the website is down.

**Comment by rminnett** [comment]
Yes, that was a temporary patch I put up during the workshop last week that displayed the contributions rather inefficiently from MongoDB. I replaced it with a query against Elasticsearch. It still reloads it every time, but since Elasticsearch caches the response, it's very quick now.

**Comment by njarboe** [comment]
Great, thanks.
