### ISSUE TITLE
Caue Borlina has uploaded Weiss et al. (2017) and the download does not work

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#80]
I wanted to check out the new upload but I get an error when I try and download. We seem to have this problem most of the time files are uploaded. If you could take a look that would be great. earthref.org/MagIC/11931

**Comment by rminnett** [comment]
This should be available for download now.

**Comment by njarboe** [comment]
The download works but the file has an extra '[a few tabs>>>>>>>>] between the specimens and measurement tables. Not sure if that was in the original upload (to you just save the file and give it back at the moment?) or some other problem. Here is a fixed version.
[magic_contribution_11931.edit.txt](https://github.com/earthref/MagIC/files/985132/magic_contribution_11931.edit.txt)

**Comment by rminnett** [comment]
That file has a lot of extra tabs at the end of the first few tables, perhaps due to a copy and paste from Excel? I removed the extra table break in the first file (I’ll have to see where that came from). Let me know if the one that is there now has any more problems.

**Comment by njarboe** [comment]
Those tabs are my fault. Opened, editied, and saved in excel. Excel does nice formatting of the columns too look at the data, but those extra tabs on save are a pain. Do use or know of a spreadsheet viewer/editor that lines up the columns but does not add those extra tabs?
