### ISSUE TITLE
Have loading icons show timeout message after a failure to load

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#87]

**Comment by rminnett** [comment]
Do you mean in the search interface when it shows 5 rows loading indefinitely?

**Comment by njarboe** [comment]
Yes. Not that important, but I would think there would be some kind of
timeout by default. This does not seem to be the case but maybe there is a
timeout parameter that is easy to set. Don't worry about this one if it is
delaying your work on the other critical improvements.

**Comment by rminnett** [comment]
Will this do for now? This update was deployed last night.

![image](https://user-images.githubusercontent.com/1182698/27145100-3d5f10f8-50e9-11e7-8cf5-395d0cecc3ff.png)

**Comment by rminnett** [comment]
But, I should also add a timeout later for when it can't connect to ElasticSearch or takes too long.

**Comment by njarboe** [comment]
Good for now. Thanks.
