### ISSUE TITLE
3.0 Data model conversion date is the same as the previous upload date.

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#90]
3.0 Data model conversion date is the same as the previous upload date. Should be the date the conversion and update to 3.0 occurred.

**Comment by rminnett** [comment]
This was intentional so that the upload order of the latest contribution was preserved, otherwise the last contributions to get upgraded would have been shown first, regardless of when they were last contributed and I didn't want authors with recent contributions to get buried.
