### ISSUE TITLE
Add link to MagIC homepage to the title text

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#92]

**Comment by rminnett** [comment]
The "M" icon links back. Are you suggesting that "Magnetics Information Consortium (MagIC)
Promoting information technology infrastructures for the international paleomagnetic, geomagnetic and rock magnetic community." should be a link, too?

**Comment by njarboe** [comment]
Yes.

**Comment by njarboe** [comment]
Most websites have the title text link to the homepage. Any reason not to
for MagIC?

**Comment by rminnett** [comment]
No, I agree. I was just making sure there wasn't somewhere else you were
referring to instead.

**Comment by njarboe** [comment]
No prob. I guess "title text" was a bit generic.
