### ISSUE TITLE
When uploading the Upload button is active when errors still exist

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#99]
When uploading the Upload button is active when errors still exist. 
![screen shot 2017-06-20 at 9 34 51 pm](https://user-images.githubusercontent.com/1278789/27367253-828b5350-5600-11e7-9530-59fc91416ac3.png)
![screen shot 2017-06-20 at 9 36 10 pm](https://user-images.githubusercontent.com/1278789/27367254-846fb508-5600-11e7-85bd-e0c7d2b11f5c.png)

**Comment by rminnett** [comment]
Are you sure they're errors and not warnings? If only warnings are present, the upload button should be enabled. If you see errors and an enabled upload button, could you tell me how to recreate that situation, please?

**Comment by njarboe** [comment]
Well, in the second screenshot above I believe those are errors as they are red and it says 10 import errors. I did not include a file to do it on as I was seeing this on all of my imports and thought it was a general error. On further investigation it looks like this happens when you turn off a whole table (table2 in the file below) the upload button appears when there are still errors.
[SheepCreekMagICUpload.xlsx](https://github.com/earthref/MagIC/files/1115894/SheepCreekMagICUpload.xlsx)
![screen shot 2017-06-30 at 9 30 02 am](https://user-images.githubusercontent.com/1278789/27745050-c3b24b04-5d76-11e7-9e04-d98bd3774586.png)

**Comment by njarboe** [comment]
Fixed.
